OT-CONTAINER-KIT/redis-operator

LICENSE, README.md
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/3
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/4
=> [Circle CI][Add] Added badges and LICENSE

CHANGELOG.md, controllers/redis_controller.go, controllers/suite_test.go, k8sutils/redis.go, k8sutils/secrets.go, k8sutils/services.go, k8sutils/statefulset.go
=> [Development][Change] Fixed linters warnings

.github/workflows/workflow.yml, helm-charts/redis-operator/crds/crd-redis.yaml
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/36
=> [BugFix][Change] Updated CRD definition in helm chart

README.md, helm-charts/redis-setup/templates/redis-setup.yaml, helm-charts/redis-setup/values.yaml
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/46
=> [BugFix][Change] Fixed helm chart API version

config/crd/bases/redis.redis.opstreelabs.in_redis.yaml
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/49
=> [BugFix][Add] Added validation for cluster count

controllers/redis_controller.go, k8sutils/redis.go
=> [Development][Feature] Added failover logic for Redis cluster

k8sutils/services.go
=> [BugFix]Fixed redis exporter service logic

k8sutils/redis-standalone.go, k8sutils/statefulset.go
=> Handle non defined storage

example/redis-standalone.yaml, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go
=> [BugFix]Fixed secret nil exception

docs/src/.vuepress/config.js, docs/src/guide/exposing-redis.md, docs/src/guide/monitoring.md, docs/src/guide/redis-cluster-config.md, docs/src/guide/redis-config.md
=> [docs][Change] Updated docs for redis operator

example/advance_config/cluster.yaml, example/advance_config/standalone.yaml, example/external_config/cluster.yaml, example/external_config/standalone.yaml, example/external_service/cluster-svc.yaml, example/external_service/cluster.yaml, example/external_service/standalone-svc.yaml, example/external_service/standalone.yaml, example/password_protected/cluster.yaml, example/password_protected/standalone.yaml, example/private_registry/cluster.yaml, example/private_registry/standalone.yaml, example/redis_monitoring/cluster.yaml, example/redis_monitoring/standalone.yaml
=> [Change]Updated example folder with streamlined examples

CHANGELOG.md, docs/src/guide/redis-cluster-config.md
=> [Change]Updated CHANGELOG and docs for v0.8.0

Makefile, SECURITY.md, api/v1beta1/common_types.go, api/v1beta1/rediscluster_types.go, config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/rbac/role.yaml, example/advance_config/cluster.yaml, example/advance_config/standalone.yaml, example/affinity/cluster.yaml, example/affinity/standalone.yaml, example/external_config/cluster.yaml, example/external_config/standalone.yaml, example/external_service/cluster.yaml, example/external_service/standalone.yaml, example/password_protected/cluster.yaml, example/password_protected/standalone.yaml, example/private_registry/cluster.yaml, example/private_registry/standalone.yaml, example/redis-cluster.yaml, example/redis_monitoring/cluster.yaml, example/redis_monitoring/standalone.yaml, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go, k8sutils/services.go
=> [Development][Remove] Removed servicetype from Operators

config/rbac/role.yaml, config/rbac/role_binding.yaml, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go
=> [BugFix] Fixed redis exporter resource block and rbac policies

.azure-pipelines/pipeline.yaml, Makefile, config/rbac/role.yaml
=> [BugFix]Fixed RBAC role for operator

controllers/rediscluster_controller.go
=> [Development][Add] Fixed service for leader and service

config/rbac/kustomization.yaml
=> Fixes 182: Adding kustomization.yaml for rbac

controllers/redis_controller.go, k8sutils/finalizer.go
Signed-off-by: Mathieu CESBRON <mathieu.cesbron@ecam-rennes.com>
=> Added finalizer

controllers/redis_controller.go, k8sutils/finalizer.go
Hello,
I add a finalizer to delete PVC resource on deletion of Redis resource, this way everything created is deleted on Redis finalize.
I will do the same for RedisCluster later if you accept it.
=> Finalize PVC resource on Redis

controllers/redis_controller.go, controllers/rediscluster_controller.go, k8sutils/poddisruption.go, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go, k8sutils/statefulset.go
Hello,
A little typo, it is `statefulSet` and not `stateFulSet`
`GetStandalone` and not `GetStandAlone`. 
=> Fix uppercase typo

k8sutils/redis-cluster.go, k8sutils/redis-standalone.go, k8sutils/services.go
Hello,
Refacto of service creation. I think it is simpler if we merge functions that create service and headlessService, tell me what you think about it.
=> Refacto service creation

.travis.yml
Signed-off-by: Mathieu Cesbron <mathieu.cesbron@ecam-rennes.com>
=> Fix travis typo

controllers/rediscluster_controller.go, k8sutils/finalizer.go
Hello,
I added the finalizer for rediscluster, I have tested it.
=> Added RedisCluster finalizer

CHANGELOG.md, docs/src/.vuepress/config.js, docs/src/guide/changelog.md, docs/src/guide/redis-cluster-config.md, docs/src/guide/redis-config.md, docs/src/guide/release.md
=> [Release]Updated release information for v0.10.0

k8sutils/finalizer.go
Hello,
I add error log that were present for redis cluster but not for redis. 
=> Add Redis finalizer error log

controllers/redis_controller.go, controllers/rediscluster_controller.go
Hello, 
Here is the PR to remove the useless owner reference.
=> Remove useless ownerReference

config/rbac/role.yaml
=> [BugFix]Fixed rbac policy for PDB 

k8sutils/statefulset.go
Signed-off-by: liortamary <lior.tamary@houzz.com>
=> [BugFix] fix panic with redisExporter enabled

example/external_service/cluster-svc.yaml
=> Fix typo of example/external_service/cluster-svc.yaml

Makefile, controllers/rediscluster_controller.go, example/disruption_budget/clusterd.yaml, k8sutils/poddisruption.go
=> [BugFix][Change] Fixed pdb creation issue

controllers/rediscluster_controller.go, k8sutils/redis.go
=> [BugFix][Change] Fixed cluster recovery logic

api/v1beta1/rediscluster_types.go, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/manager/kustomization.yaml, k8sutils/redis.go
Signed-off-by: Tanuj Dwivedi <dwiveditanuj41@gmail.com>
=> Support for Single Leader and Follower in Cluster setup

k8sutils/statefulset.go
resize pvc
// 1.Get the data already stored internally
// 2.Get the desired data
// 3.Start querying the pvc list when you find data inconsistencies
// 3.1 Comparison using real pvc capacity and desired data
// 3.1.1 Update if you find inconsistencies
// 3.2 Writing successful updates to internal
// 4. Set to old VolumeClaimTemplates to update.Prevent update error reporting
// 5. Set to old annotations to update
=> [feature]resize pvc

k8sutils/redis.go
=> [BugFix]Fixed IP check logic for conversion

k8sutils/finalizer.go
=> [Add]Added code for statefulset finalizer

k8sutils/labels.go
=> [BugFix]Added prometheus service annotation

Dockerfile
=> [BugFix][Add] Added build arg for arm64 support

config/manager/manager.yaml
=> [BugFix]Updated the security context for controller manager

controllers/rediscluster_controller.go
=> [Development][Add] Added logic for updating followers replicas

k8sutils/redis-standalone.go
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>
=> [feature]add tls for redis-standlone

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, SECURITY.md, docs/content/en/docs/Release History/_index.md
=> [Development][Update]Updated information for v0.13.0

k8sutils/redis-cluster.go
Signed-off-by: ylck [ylck77@gmail.com](mailto:ylck77@gmail.com)
Description
Check PersistenceEnabled for cluster fix https://github.com/OT-CONTAINER-KIT/redis-operator/issues/378
=> [BugFix] Add check PersistenceEnabled not nil

api/v1beta1/common_types.go, api/v1beta1/rediscluster_types.go, config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go
Fixes: #394,#383
Signed-off-by: lvyanru <yanru.lv@daocloud.io>
Fixes #ISSUE
**Checklist**
=> fix: invalid memory address or nil pointer dereference

example/affinity/clusterd.yaml
Adding a pod anti-affinity so that leader and follower are not placed together.
=> Add Label Selector to pod anti affinity 

k8sutils/redis-sentinel.go, k8sutils/services.go
Fixes #434
Fixes #435
**Checklist**
=> Fixed StatefulSet(sentinel) Label for Service(Selector) #434 #435

k8sutils/statefulset.go
=> Optimize pvcTemplate Name for Storage #438

README.md
Added helm command to uninstall resources.
=> Updated README.md to add delete commands 

api/v1beta1/redissentinel_types.go, k8sutils/redis-sentinel.go
Signed-off-by: muicoder <muicoder@gmail.com>
Feature: Add RedisExporter for sentinel
**Checklist**
=> [Feature] Add RedisExporter for sentinel

.azure-pipelines/pipeline.yaml, Makefile, config/manager/kustomization.yaml
Update the Current Version from 
`v0.14.0 to v0.15.0 `
=> Upgrade version

.azure-pipelines/pipeline.yaml, k8sutils/statefulset.go
=> Fix : Redis Sentinel Exporter ports in Env Vars

api/v1beta1/redissentinel_types.go, config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml
=> Fix sentinel default validation not effect

example/tolerations/replication.yaml, example/upgrade-strategy/replication.yaml
=> Add redis replication yaml example

controllers/redissentinel_controller.go, example/redis-sentinel.yaml, k8sutils/poddisruption.go
Add redis sentinel pdb reconcile.
**Checklist**
=> [Add]- Support redis sentinel pdb

docs/content/en/docs/Advance Configuration/TLS and Security/_index.md
Fix the bad image path
**Checklist**
=> Fix image path

.github/ISSUE_TEMPLATE/documentation_update.md, .github/ISSUE_TEMPLATE/general_question.md, .github/PULL_REQUEST_TEMPLATE.md
Update the issue and PR template. 
Adding new general questions & Docs issue. 
**Checklist**
=> Refactor : issue and pr templates

api/rbac.go
move the RBAC to /api
**Checklist**
=> Move rbac.go

Makefile
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/600
**Checklist**
=> Support apply crds by kubectl apply --server-side

config/crd/kustomization.yaml, config/crd/patches/webhook_in_redis.yaml, config/crd/patches/webhook_in_redisclusters.yaml, config/crd/patches/webhook_in_redisreplications.yaml, config/crd/patches/webhook_in_redissentinels.yaml, config/default/kustomization.yaml
=> fix : kustomize install

.github/workflows/operator-ci.yaml
Removed duplicate Arm/Amd Image build from Github action 
Fixes #593
=> [Refactor]:  operator-ci.yaml Github action

controllers/redissentinel_controller.go
As description in https://github.com/drivebyer/redis-operator-1/blob/master/docs/content/en/docs/Installation/Upgradation/_index.md, we should support redissentinel can skip reconcile by adding annotation.
**Checklist**
=> Support redissentinel can skip reconcile loop

k8sutils/redis-sentinel.go
Support recreate statefulset of redissentinel
**Checklist**
=> Support recreate statefulset of redissentinel

example/backup_restore/configmap.yaml, example/backup_restore/env-secret.yaml, example/backup_restore/redis-cluster.yaml, scripts/backup/backup.md, scripts/backup/manifest/kubectlpod.yaml, scripts/env_vars.env, scripts/restore/Dockerfile.restore, scripts/restore/restore.bash, scripts/restore/restore.md
1.  Skip the restore criteria from the follower pods. 
2.  Add Manifest to the examples. 
3.  Small bug fixes
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/610
**Checklist**
=> [Bug]: Restore script 

api/rbac.go, api/status/redis-cluster_status.go, api/v1beta2/rediscluster_types.go, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/rbac/role.yaml, controllers/rediscluster_controller.go, k8sutils/status.go
=> [Fix] : Status Field to Redis Cluster

.github/workflows/operator-ci.yaml, api/v1beta2/redis_webhook.go, api/v1beta2/rediscluster_webhook.go, api/v1beta2/redisreplication_webhook.go, api/v1beta2/redissentinel_webhook.go, controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, k8sutils/poddisruption.go, k8sutils/redis.go, k8sutils/services.go, k8sutils/statefulset.go
Change `golangci-lint` from manual installation to gh-actions
Fixes #648 
**Checklist**
**Additional context**
Take a look at https://github.com/titanventura/ot-container-kit-redis-operator/actions/runs/6395766402 and https://github.com/titanventura/ot-container-kit-redis-operator/actions/runs/6395703984 to know more about how the change fits in !
=> Golang ci lint action

go.mod, k8sutils/services_test.go, k8sutils/statefulset_test.go
Add more go test case for better testing and coverage
=> [Test] : Add test files 

tests/e2e/v1beta2/setup/redis-standalone/00-install.yaml, tests/e2e/v1beta2/setup/redis-standalone/ready-pvc.yaml, tests/e2e/v1beta2/setup/redis-standalone/ready-sts.yaml, tests/e2e/v1beta2/setup/redis-standalone/standalone.yaml
part of : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> [Test] : e2e Redis Standalone test 

Makefile, api/rbac.go, config/certmanager/certificate.yaml, config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml, config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml, config/crd/patches/webhook_in_redis.yaml, config/crd/patches/webhook_in_redisclusters.yaml, config/crd/patches/webhook_in_redisreplications.yaml, config/crd/patches/webhook_in_redissentinels.yaml, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/default/manager_webhook_patch.yaml, config/prometheus/monitor.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/webhook/service.yaml
selftest:
```
➜  redis-operator-1 git:(deploy-target) make deploy                  
/Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && /Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/bin/kustomize edit set image controller=quay.io/opstree/redis-operator:v0.15.0
/Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/bin/kustomize build config/default | kubectl apply --server-side=true -f -
namespace/redis-operator-system serverside-applied
customresourcedefinition.apiextensions.k8s.io/redis.redis.redis.opstreelabs.in serverside-applied …
```
=> [Fix] - make deploy target not works well

.github/workflows/operator-ci.yaml
Since we are writing the unit test for this repo. 
I hope we able to see the improvement here
=> [Workflow] : Add code coverage reports

.github/workflows/operator-ci.yaml, tests/e2e/v1beta2/setup/redis-replication/00-install.yaml, tests/e2e/v1beta2/setup/redis-replication/ready-pvc.yaml, tests/e2e/v1beta2/setup/redis-replication/ready-sts.yaml, tests/e2e/v1beta2/setup/redis-replication/ready-svc.yaml, tests/e2e/v1beta2/setup/redis-replication/replication.yaml
Related to : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
**Checklist**
=> [Test] : add redis replication setup case

tests/e2e/v1beta2/setup/redis-cluster/00-install.yaml, tests/e2e/v1beta2/setup/redis-cluster/ready-svc.yaml, tests/e2e/v1beta2/setup/redis-standalone/00-install.yaml, tests/e2e/v1beta2/setup/redis-standalone/ready-svc.yaml
Related https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> [Test] : add assert service to setup

k8sutils/redis-standalone_test.go, k8sutils/statefulset.go, tests/testdata/redis-standalone.yaml
Part of : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> test : Add Unit Test for redis-standalone.yaml 

Makefile, tests/_config/kind-config.yaml
Add targets in makefile to perform e2e Test
=> makefile : Add Target to run e2e Test 

k8sutils/redis-cluster.go, k8sutils/redis-cluster_test.go, k8sutils/redis-replication_test.go, k8sutils/redis-sentinel.go, k8sutils/redis-sentinel_test.go, k8sutils/statefulset.go, tests/testdata/redis-cluster.yaml, tests/testdata/redis-replication.yaml, tests/testdata/redis-sentinel.yaml
related: https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> test: add test for redisreplication/redissentinel/rediscluster

.github/workflows/release-images.yaml
=> fix: Typo in release

mocks/client/client_mock.go
=> Add : Mock Client

controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, k8sutils/finalizer.go, k8sutils/finalizers_test.go, main.go
part of : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> fix : Add client for Testing

.github/workflows/e2e.yaml, k8sutils/finalizer.go, k8sutils/finalizers_test.go, tests/_config/kuttl-test.yaml, tests/e2e/v1beta2/teardown/redis-cluster/00-install.yaml, tests/e2e/v1beta2/teardown/redis-cluster/01-uninstall.yaml, tests/e2e/v1beta2/teardown/redis-cluster/cluster.yaml, tests/e2e/v1beta2/teardown/redis-cluster/ready-cluster.yaml, tests/e2e/v1beta2/teardown/redis-cluster/ready-pvc.yaml, tests/e2e/v1beta2/teardown/redis-cluster/ready-sts.yaml, tests/e2e/v1beta2/teardown/redis-cluster/ready-svc.yaml, tests/e2e/v1beta2/teardown/redis-replication/00-install.yaml, tests/e2e/v1beta2/teardown/redis-replication/01-uninstall.yaml, tests/e2e/v1beta2/teardown/redis-replication/ready-pvc.yaml, tests/e2e/v1beta2/teardown/redis-replication/ready-sts.yaml, tests/e2e/v1beta2/teardown/redis-replication/ready-svc.yaml, tests/e2e/v1beta2/teardown/redis-replication/replication.yaml, tests/e2e/v1beta2/teardown/redis-sentinel/00-install.yaml, tests/e2e/v1beta2/teardown/redis-sentinel/01-uninstall.yaml, tests/e2e/v1beta2/teardown/redis-sentinel/ready-sts.yaml, tests/e2e/v1beta2/teardown/redis-sentinel/ready-svc.yaml, tests/e2e/v1beta2/teardown/redis-sentinel/sentinel.yaml, tests/e2e/v1beta2/teardown/redis-standalone/00-install.yaml, tests/e2e/v1beta2/teardown/redis-standalone/01-uninstall.yaml, tests/e2e/v1beta2/teardown/redis-standalone/ready-pvc.yaml, tests/e2e/v1beta2/teardown/redis-standalone/ready-sts.yaml, tests/e2e/v1beta2/teardown/redis-standalone/ready-svc.yaml, tests/e2e/v1beta2/teardown/redis-standalone/standalone.yaml
part of : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> [Fix] : redis data pvc not deleted

.github/workflows/e2e-chainsaw.yml, tests/_config/chainsaw-configuration.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/teardown/redis-cluster/ready-svc.yaml
=> feat: Add Chainsaw Action in CI 

tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml
=> test: try Ping cluster

.github/workflows/e2e-chainsaw.yml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/password/redis-cluster/secret.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml
=> test: Setting Password on Redis Cluster

tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/sentinel.yaml
=> test: Add Sentinel Setup

controllers/redis_controller_test.go, controllers/rediscluster_controller_test.go, controllers/suite_test.go, k8sutils/redis-cluster.go
Add integration tests for redis cluster.
**Checklist**
=> Add redis cluster integration tests

controllers/redissentinel_controller_test.go, controllers/suite_test.go
Add redis sentinel integration tests (last one).
**Checklist**
=> Add redis sentinel integration tests

controllers/redissentinel_controller_test.go
Remove useless comment that should never have been here.
**Checklist**
=> Remove useless comment

CODEOWNERS
=> add: codeowners

Makefile, controllers/redissentinel_controller.go, k8sutils/finalizer.go, k8sutils/finalizers_test.go, k8sutils/log/log.go
Add unit Testing Covering finalizers.go
=> test: Add Finalizers Unit Test

.github/workflows/pr-semantics.yaml
=> ci: add deps scope in pr semantics

k8sutils/client.go, k8sutils/redis.go, main.go
Refactor Code and use interface for testing the code
=> refactor(client): Use interface

go.mod, go.sum, k8sutils/client.go, k8sutils/cluster-scaling.go, k8sutils/cluster-scaling_test.go
Add redis mock client for testing the result from the redis
=> test(client): Add redis mock client

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go
Remove useless comments on all reconcile functions. 
**Checklist**
=> Remove useless comments

k8sutils/statefulset_test.go
test: cover func enableRedisMonitoring
=> test: cover func enableRedisMonitoring

k8sutils/statefulset_test.go
test: cover generateInitContainerDef
=> test: cover generateInitContainerDef

main.go
=> feat: WATCH_NAMESPACE support multi namespace

.github/workflows/publish-image.yaml
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/actions/runs/9079763715/job/24949664940
=> build: repository name must be lowercase

k8sutils/statefulset_test.go
test: cover generateContainerDef
=> test: cover generateContainerDef

k8sutils/statefulset_test.go
generateStatefulSetsDef test case
=> test: generateStatefulSetsDef cover

charts/redis-operator/Chart.yaml, charts/redis-operator/readme.md, charts/redis-operator/templates/operator-deployment.yaml, charts/redis-operator/templates/service-account.yaml, charts/redis-operator/values.yaml
=> feat: add automountServiceAccountToken values for deployment and serviceaccnount

k8sutils/statefulset_test.go
=> test: cover getSidecars

docs/content/en/docs/Getting Started/Cluster/_index.md, docs/content/en/docs/Getting Started/Replication/_index.md, docs/content/en/docs/Getting Started/Sentinel/_index.md, docs/content/en/docs/Getting Started/Standalone/_index.md
=> docs: fix example broken links

charts/redis-replication/Chart.yaml, charts/redis-replication/templates/redis-replication.yaml
=> fix: indention error when enable additional config

.github/workflows/publish-charts.yaml
Reverts OT-CONTAINER-KIT/redis-operator#1070
=> Revert "chore(deps): bump helm/kind-action from 1.5.0 to 1.10.0"

charts/redis-cluster/Chart.yaml, charts/redis-cluster/README.md, charts/redis-cluster/values.yaml, charts/redis-replication/Chart.yaml, charts/redis-replication/README.md, charts/redis-replication/values.yaml, charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/README.md, charts/redis-sentinel/values.yaml, charts/redis/Chart.yaml, charts/redis/README.md, charts/redis/values.yaml, docs/content/en/docs/Advance Configuration/Upgrading/_index.md, docs/content/en/docs/Configuration/Redis/_index.md, docs/content/en/docs/Configuration/RedisCluster/_index.md, docs/content/en/docs/Configuration/RedisReplication/_index.md, docs/content/en/docs/Getting Started/Cluster/_index.md, docs/content/en/docs/Getting Started/Replication/_index.md, docs/content/en/docs/Getting Started/Sentinel/_index.md, docs/content/en/docs/Getting Started/Standalone/_index.md
=> feat: upgrade redis/sentinel image to 7.0.15

Dockerfile
Fix dockerfile casing
Fixes #ISSUE
**Checklist**
=> fix: dockerfile casing

pkg/agent/bootstrap/generate_redis_config.go
This commit adds a detailed implementation of Redis configuration generation with support for:
- Cluster and standalone modes
- TLS configuration
- ACL setup
- Persistence options
- Port and network configurations
- Dynamic IP and hostname resolution
- External configuration file inclusion
The implementation uses environment variables to customize Redis configuration dynamically and handles various deployment scenarios.
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/766
**Checklist**
=> feat: Implement comprehensive Redis configuration generation for agent bootstrap

pkg/k8sutils/statefulset.go, pkg/k8sutils/statefulset_test.go
Enhance Redis Operator with Controlled PreStop Failover for Cluster Mode
This PR introduces a **PreStop hook** for **Redis Cluster mode** in the Redis Operator to prevent unexpected master failover during StatefulSet rolling updates. Ref: #1262
When a Redis master pod is terminated during a rolling update, **passive failover** occurs, which can lead to temporary service disruptions. The goal of this PR is to ensure a **manual failover** before termination by:
- Checking if the pod is a **master**.
- Identifying the **slave with the highest replication offset**.
- Triggering a **manual failover** before the pod shuts down.
1. **Added `preStop` Hook for Cluster Mode**  
- Implemented in `generateContainerDef()`.
- PreStop command is dynamically generated using `GeneratePreStopCommand()`.
- …
=> feat: Add preStop hook for Redis Cluster failover and unit tests

pkg/util/map.go
Make the Merge Map function genralize.
=> refactor(utils): Genralize MergeMap function to support any key-value types

Makefile
Improve the makefile clubbed the variable section, targets, depedency and added some comment over the targets.
**Checklist**
=> chore(utils):  Update Makefile

Makefile
=> feat: Add docker-load target to Makefile for loading images into Docker

pkg/agent/bootstrap/generate_sentinel_config.go
Relate to [95](https://github.com/OT-CONTAINER-KIT/redis/pull/95) in image repository
=> Sentinel - announce-ip <hostname> when resolve & announce are set

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/publish-charts.yaml, .github/workflows/publish-image.yaml, .github/workflows/verify-codegen.yaml, .travis.yml, CONTRIBUTING.md, README.md, charts/redis-cluster/Chart.yaml, charts/redis-operator/Chart.yaml, charts/redis-replication/Chart.yaml, charts/redis-sentinel/Chart.yaml, charts/redis/Chart.yaml, ct.yaml, docs/content/en/docs/Configuration/Redis/_index.md, docs/content/en/docs/Configuration/RedisCluster/_index.md, docs/content/en/docs/Configuration/RedisReplication/_index.md, docs/content/en/docs/Getting Started/Cluster/_index.md, docs/content/en/docs/Getting Started/Replication/_index.md, docs/content/en/docs/Getting Started/Sentinel/_index.md, docs/content/en/docs/Getting Started/Standalone/_index.md, docs/content/en/docs/Installation/Create Cluster/_index.md, docs/content/en/docs/Installation/Upgradation/_index.md, docs/content/en/docs/Monitoring/_index.md, docs/content/en/docs/Overview/_index.md
=> fix: update references from master to main in docs and workflow files

pkg/k8sutils/statefulset.go
1. create a `RedisReplication` CRD & wait for it to create the corresponding `StatefulSet`
1. add a new annotation to the `RedisReplication` CRD (anything will do)
1. watch it go into an infinite loop unable to reconcile the `VolumeClaimTemplate` part
With the default log level it's not initially obvious what's happening, so it might be worth adding `--zap-devel` to the argument list.
You will notice the `banzaicloud.com/last-applied` annotation changing. `kubectl get sts --watch` and/or `k8s` audit logs all will show the continuous updates.
The issue is that the diffing logic happens before the VCT modification happens.
So this calculates a diff which includes e.g a new annotation, and the patch is non-empty:
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/5ea1410f20b31b0711b154fa …
=> fix: move VCT logic before diff calculation for stateful set

Makefile, charts/redis-operator/Chart.yaml
=> chore: bump version to 0.20.1

example/v1beta2/password_protected/sentinel.yaml
re: https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1318
=> docs: re: issues/1318 - example for authenticated RedisSentinel

.github/workflows/ci.yaml, Makefile, tests/data-assert/main.go, tests/data-assert/resources.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-ha/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-ha/ha.yaml
- Updated Makefile to include new targets for generating data assertions and metrics documentation.
- Enhanced main.go in data-assert to support a new flag for Redis sentinel password.
- Added new test cases for Redis high availability setup, including master IP consistency checks and data assertions.
These changes improve the testing capabilities and configuration management for Redis deployments.
Fixes #ISSUE
**Checklist**
=> feat: add data assertion generation and enhance Redis configuration commands

charts/redis-operator/templates/operator-deployment.yaml
=> fix: define named probe port outside webhook block (#1353)

docs/content/en/docs/Release History/_index.md
Update release history in the docs
Fixes #1452 
**Checklist**
=> docs: Update release history

README.md, docs/content/en/docs/Overview/_index.md
Fix a couple obsolete links, remove references to obsolete documentation
=> docs: Fix obsolete links

.github/workflows/call-test-charts.yaml, .github/workflows/ci.yaml, .github/workflows/publish-charts.yaml, charts/redis-operator/README.md, charts/redis-operator/templates/operator-deployment.yaml, charts/redis-operator/values.yaml, tests/_config/chainsaw-configuration.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-ha/chainsaw-test.yaml
- Use explicit float comparison (0.0) in deployment template
- Update values.yaml kubeClientQPS default from 0 to 0.0 for type consistency
- Ensures proper float64 type handling in Helm template condition
Fixes #ISSUE
**Checklist**
=> fix: improve kubeClientQPS type consistency in operator chart
