OT-CONTAINER-KIT/redis-operator

k8sutils/services.go
For redis-master and redis-slave services pod selector. See issue #79.
=> Removed conflicting redis=monitor label

k8sutils/redis.go
Command output was being continuously appended for each execution, making logging and debugging extremely difficult to understand which portion related to what output.
This now ensures that the variables are clean on each execution.
=> Fix issue where command output was continuously being appended

controllers/redis_controller.go, k8sutils/client.go, k8sutils/redis.go, k8sutils/statefulset.go
Whilst trialing this operator I found the following issues:
- If the cluster failed to be created, the slaves/followers, where subsequently joined to their pair, and unable to join the cluster at a later date due to data.
Therefore, waiting/ensuring the cluster is created, helps to ensure that everything is in order and the cluster can be formed successfully.
- `STDERR` was missing when a command failed, this is now printed out to help debugging.
- When checking for failed nodes, a string regex search was being used... but what if a node was called similar.. this would end up in a state of constant fail.. Taken from the redis docs [cluster nodes](https://redis.io/commands/cluster-nodes#serialization-format)
> The output of the command is just a space-separated CSV string, where each line …
=> Improve cluster provisioning logic

docs/src/guide/exposing-redis.md, docs/src/guide/redis-cluster-config.md, docs/src/guide/redis-config.md
1. Remove `serviceType` configuration from docs due to [these changes](https://github.com/OT-CONTAINER-KIT/redis-operator/pull/148)
2. Fix anchor and markdown
=> Update and fix docs due to recent changes

config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
It's wasn't implement in my previous commit, so sidecar wasn't supported with the kubectl setup and files on this repo
=> Implement sidecar to crd redis object

main.go
This add option to have an operator that do not need cluster-wide rights. If env var `NAMESPACE` is present, operator will watch resources in this namespace and not cluster-wide.
I have tested it and it work.
#187
=> Added option for namespaced operator

config/rbac/kustomization.yaml
Looks like there's a copy/paste error from the prometheus kustomization? This one fails to build because `monitor.yaml` doesn't exist.
=> Fix invalid RBAC kustomization

docs/src/guide/installation.md
In the previous order of kubectl, the third "kubectl apply" would give us an error:
```
$ kubectl apply -f https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/config/rbac/serviceaccount.yaml
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/config/rbac/serviceaccount.yaml": namespaces "redis-operator" not found
```
The commit reorder "kubectl apply" to have a working redis-operator at the end.
=> Reorder kubectl apply (documentation error)

dashboards/redis-operator-cluster.json
On Grafana, I have multiple redis cluster exporters that coming from Prometheus. Because of this, on this dashboard I see all Redis servers without filtering. And I need to filter by environment variable. So I added "Environment" combo box on top of the dashboard. And, added env filter to queries of all panels on dashboard. It runs very well on my Grafana. And I would like to bring this feature to this dashboard.
Signed-off-by: tayyiposmanoglu <osmanogluta@itu.edu.tr>
=> combo box added to dashboard to filter values by environment

k8sutils/statefulset.go
This pull request removes some obsolete code that leads to nil-pointer reference when the field `kubernetesConfig.resources` and other `resources` fields are unspecified.
The detailed information and steps to reproduce the crash have been explained in https://github.com/OT-CONTAINER-KIT/redis-operator/issues/283.
=> Fix: Crash if fields `resources` are not present

k8sutils/redis.go
This pull request serves as a naive patch to the crashing problem when `targetContainer` does not exist. 
Specifically, the operator crashes when it cannot find the pod to execute command on. When the pod being queried does not exist, `getContainerID` returns '-1'. The operator detects the error, but instead of aborting immediately, it continues to access `pod.Spec.Containers[]` with index `targetContainer`, leading to a crash.
```shell
1.6543661422595975e+09	ERROR	controller_redis	Could not find pod to execute	{"Request.RedisManager.Namespace": "default", "Request.RedisManager.Name": "test-cluster"}
redis-operator/k8sutils.ExecuteRedisClusterCommand
/workspace/k8sutils/redis.go:71
redis-operator/controllers.(*RedisClusterReconciler).Reconcile …
```
=> fix: crash if targetContainer does not exist

config/manager/manager.yaml, main.go
resolved #305 
Can check with this command
go run main.go -zap-log-level [level]
[flag] -zap-log-level value: Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
ref) https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/
By passing args to the spec part of deployment, the log level can be set.
e.g)
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/config/manager/manager.yaml
At line 31
```yaml
args:
- --leader-elect
- --zap-log-level=debug
```
=> Update zap options to support specifying log level

config/rbac/role.yaml
Signed-off-by: zmrdltl <meenseek5929@naver.com>
resolved #312 
The go operator logic is implemented, ref : https://github.com/OT-CONTAINER-KIT/redis-operator/pull/204
but since pv and pvc are not added to clusterrole, they are not deleted together when CR is deleted. I solved this.
=> Add pvc, pv clusterrole for deletion

k8sutils/redis.go
I noticed that there is a goroutine leak due to opening redis client connections and never closing or reusing them.  The goroutine count with a single cluster was increasing by about 2 per reconcile.  The following shows the before/after count of redis connection goroutines.
This will ensure the redis client connections get closed which fixes the goroutine leak.
<details><summary>Before</summary><br><pre>
$ while true                                                                                                                                                                                                                                                                                                                                 
do
curl -s …
=> Close redis client connections

Makefile, controllers/redis_controller.go, controllers/rediscluster_controller.go, example/redis_monitoring/clusterd.yaml, example/redis_monitoring/standalone.yaml
=> [Development][Add] Added option to pause reconcilations

.gitignore, k8sutils/redis.go
Fix this:
When we have:
* leader: [xxx-leader-0, xxx-leader-1, xxx-leader-2]
* follower: [xxx-follower-0, xxx-follower-1, xxx-follower-2, xxx-follower-3, xxx-follower-4, xxx-follower-5]
[xxx-follower-3, xxx-follower-4, xxx-follower-5] can not join cluster.
=> fix: lost replications when followerReplicas bigger than leaderReplicas

k8sutils/redis-cluster.go, k8sutils/redis-standalone.go
`service` and `annotations`  may not be present in all KubernetesConfig. This PR adds a check to only add the annotations
if the service block actually exists in the KubernetesConfig
Fixes #381
**Checklist**
=> fix crash with go panic

k8sutils/services.go, k8sutils/statefulset.go
Exposes the `redis-exporter` port as a named port for the container.
Fixes #386
**Checklist**
=> Expose redis exporter port as a container port

CHANGELOG.md, k8sutils/statefulset.go
When Cr annotations updated, the VolumeClaimTemplates's annotations update everyTime
```go
if !apiequality.Semantic.DeepEqual(newStateful.Spec.VolumeClaimTemplates, storedStateful.Spec.VolumeClaimTemplates) {
// resize pvc
// 1.Get the data already stored internally
// 2.Get the desired data
// 3.Start querying the pvc list when you find data inconsistencies
// 3.1 Comparison using real pvc capacity and desired data
// 3.1.1 Update if you find inconsistencies
// 3.2 Writing successful updates to internal
// 4. Set to old VolumeClaimTemplates to update.Prevent update error reporting
// 5. Set to old annotations to update
annotations := storedStateful.Annotations
if annotations == nil {
annotations = map[string]string{
"storageCapacity": "0",
}
}
```
will go in.
and end of …
=> When cr annotation update,sts annotations will not updated!

Dockerfile, Makefile
This PR adds support for multi-architecture container images. I am not sure of the CI flow but rather than reusing the existing make targets (e.g. `docker-build`), I could create new make targets for the `docker builds` commands but wanted to get the conversation started before making any assumptions.
Fixes #390 
**Checklist**
=> Fixes issue with arm64 support.

Makefile, example/eks-cluster.yaml, example/recreate-statefulset/clusterd.yaml, example/recreate-statefulset/standalone.yaml, k8sutils/redis-cluster.go, k8sutils/redis-standalone.go, k8sutils/statefulset.go
=> [Development][Add] Added recreation logic for statefulset

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/suite_test.go, go.mod, k8sutils/finalizer.go, k8sutils/labels.go, k8sutils/poddisruption.go, k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-standalone.go, k8sutils/redis.go, k8sutils/redis_test.go, k8sutils/secrets.go, k8sutils/statefulset.go, main.go
Fixes the inability to import this go module.
```
github.com/OT-CONTAINER-KIT/redis-operator/api/v1beta1: github.com/OT-CONTAINER-KIT/redis-operator@v0.13.0: parsing go.mod:
module declares its path as: redis-operator
but was required as: github.com/OT-CONTAINER-KIT/redis-operator
```
=> declare module correctly

k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-standalone.go
=> fix: exporter ports enabled even when exporters disabled

k8sutils/statefulset.go
This reverts commit ff6980f6bd8c1191778cc065b1d18f11f58383a7.
Fixes [#ISSUE](https://github.com/OT-CONTAINER-KIT/redis-operator/issues/507)
This revert fixes:
* breaking change of existing StatefulSet volume names
* prevent data loss of existing persistent redis deployments
Moreover there is no any "Optimize" required around PVC names:
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
>contain no more than **253 characters**
**Checklist**
=> Revert "Optimize pvcTemplate Name for Storage #438 (#445)"

k8sutils/finalizer.go, k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-standalone.go, k8sutils/statefulset.go
Fixes: https://github.com/OT-CONTAINER-KIT/redis-operator/issues/470
Fixes: https://github.com/OT-CONTAINER-KIT/redis-operator/issues/409
Fixes : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/421
Fixes : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/450
_Note: The PV is created using the default storage class. If the default storage class is missing then this might throw an error._ 
**Checklist**
=> Fix Bug : Operator Crash when persistence is false/Disabled

main.go
This PR add watchnamespace function. To activate it add to manager.yaml in section containers:
```
env:
- name: WATCH_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
```
=> add watchnamespace function

k8sutils/redis-sentinel.go
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/521
=> [Bug] Fix the call of func checkAttachedSlave for 1 Master Replication

k8sutils/statefulset.go
This fixes an issue introduced by #519 where the `node-conf` volume would be mounted in `Replication` and `Standalone` containers, despite not having the relevant `PersistentVolumeClaim`:
```go
if containerParams.PersistenceEnabled != nil && params.ClusterMode {
statefulset.Spec.VolumeClaimTemplates = append(statefulset.Spec.VolumeClaimTemplates, createPVCTemplateNodeConf(stsMeta))
}
```
Fixes #524
**Checklist**
=> fix: Only created `/node-conf` VolumeMount for clusters

api/v1beta1/redissentinel_types.go
There is not `Not` validation in kubebuilder. We can use `Enum` to limit sentinel size to some odd number. https://book.kubebuilder.io/reference/markers/crd-validation.html
**Checklist**
=> Feat: sentinel cluster size must be odd number

.azure-pipelines/pipeline.yaml, k8sutils/statefulset.go
Init Container should mount the same volume as the primary ( redis )  container. 
Fixes : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/537
=> Bug Fix : Init Container tried to mount  invalid volume name 

.azure-pipelines/pipeline.yaml, controllers/rediscluster_controller.go, k8sutils/cluster-scaling.go, k8sutils/redis.go
Fixes #531
* Fixes the Check Master 
* Fix the func VerifyLeaderPod
* Add Follower by proper indexing using func ExecuteRedisReplicationCommand
**Checklist**
=> [Bugs] [ Refactor ] - Redis Cluster Scaling 

k8sutils/finalizer.go
RedisCluster and RedisReplication PVCs are not removed with CR
**Checklist**
=> Fix finalizePVC name mismatch

.azure-pipelines/pipeline.yaml, controllers/rediscluster_controller.go
Redis Cluster would go down in the broken state if the leader = 1 and follower = 0. 
This PR tries to prevent that broken state. 
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/497
**Checklist**
=> [Fix] - Cluster leader failover loop if there is only a single leader

k8sutils/finalizer.go
Signed-off-by: muicoder <muicoder@gmail.com>
because of CRs ownerReferences have already been associated
The finalizers e.g.  `redisFinalizer` 
is added to Redis ( Custom Resource ), not the sts or the services, we already have added `ownerReferences` to the sts, service and other component which make sure deletion in every case so having function 
```
if err := finalizeRedisServices(cr); err != nil {
return err
}
```
or 
```
if err := finalizeRedisStatefulSet(cr); err != nil {
return err
}
```
are not useful anymore because the basic operation they perform is to delete the object i.e. services and sts. 
For now we are removing the finalizers from the code as unused operations were being performed. 
Refactor - This won't break the functionality of the …
=> [Refactor] - Remove redundant finalizers from operator

README.md
We might be a bit slow to answer on GitHub. Want a quicker chat? Say hi on our Slack:
[Join our #redis-operator Slack Channel](https://opstree.slack.com/archives/C05MBRB50JG).
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/580
**Checklist**
=> Add Slack Joining Link to Repo

k8sutils/const.go, k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-standalone.go
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/362
**Checklist**
=> [Feature] - Auto recreate redis replication statefulset when update failed

k8sutils/cluster-scaling.go, k8sutils/finalizer.go, k8sutils/poddisruption.go, k8sutils/redis-sentinel.go, k8sutils/redis.go, k8sutils/secrets.go, k8sutils/services.go, k8sutils/statefulset.go, main.go
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/430
Add log verbosity param && level down some logger.
**Checklist**
=> [Enhancement]- Fix log pollution

config/rbac/role.yaml
Add missing resources `redisreplications` and `redissentinels` to the ClusterRole.
Fixes #526 
**Checklist**
verified role update directly in the clusterrole in an openshift 4.11 cluster.
=> Fixes #526 Add RBAC for redisreplications and redissentinels.

main.go
When run operator locally, we may not use webhook server usaually, then we can provide option to disable webhook server, just like: https://github.com/kubernetes-sigs/controller-runtime/issues/491#issuecomment-617028704
**Checklist**
=> Support ENABLE_WEBHOOKS env which cloud disable webhook server locally

api/v1beta2/redis_types.go, api/v1beta2/rediscluster_types.go, api/v1beta2/redisreplication_types.go, api/v1beta2/redissentinel_types.go, example/v1beta2/env_vars/redis-cluster.yaml, example/v1beta2/env_vars/redis-replication.yaml, example/v1beta2/env_vars/redis-sentinel.yaml, example/v1beta2/env_vars/redis-standalone.yaml, example/v1beta2/redis-cluster.yaml, k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-standalone.go, k8sutils/statefulset.go
Fixes #630 
You can now add extra env field under to spec to configure additionalEnvs 
For ex:  under Spec section you can add  ```  env:
- name: CUSTOM_ENV_VAR_1
value: "custom_value_1"
- name: CUSTOM_ENV_VAR_2
value: "custom_value_2"  ```
**Checklist**
=> [Feature] : Added Custom EnvVars support

k8sutils/statefulset.go
Resize pvc for RedisCluster
1. pvc for RedisCluster have labels：
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: xxxx
labels:
app: test-redis-c-leader
app.kubernetes.io/component: redis
app.kubernetes.io/name: test-redis-c
redis_setup_type: cluster
role: leader
```
Here `app` is sts's Name,app. `kubernetes.io/name` is CR's name,so we match label just `app` and `redis`
Fixes #ISSUE
Bug fix
* Bug fix 
**Checklist**
=> fix:resize cluster's pvc with wrong label

api/v1beta1/redissentinel_conversion.go, example/v1beta2/redis-cluster.yaml, k8sutils/redis-sentinel.go
This PR fixes the nil ptr error that panic the operator when the `redisSentinelConfig` field is empty
**Checklist**
=> [Fix]  nil ptr when sentinel config is emtpy

.golangci.yml, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, go.mod, go.sum, k8sutils/cluster-scaling.go, k8sutils/redis-sentinel.go, k8sutils/redis.go
=> Redis SDK version update

tests/e2e/v1beta2/setup/ready-cluster.yaml, tests/readme.md
```
➜  redis-operator git:(fix-e2e) kubectl kuttl test ./tests/e2e/v1beta2 --config ./tests/_config/kuttl-test.yaml --timeout 10m
Error: invalid argument "10m" for "--timeout" flag: strconv.ParseInt: parsing "10m": invalid syntax
```
**Checklist**
=> Fix e2e test

k8sutils/poddisruption.go, k8sutils/services.go, k8sutils/statefulset.go
Introduce by https://github.com/OT-CONTAINER-KIT/redis-operator/pull/653
err will be set to nil. Statefulset would not be created as well.
**Checklist**
=> [Fix] - sts will never be created

.github/workflows/e2e.yaml, Makefile, config/manager/kustomization.yaml, config/manager/manager.yaml
This is the correct version of: https://github.com/OT-CONTAINER-KIT/redis-operator/pull/579/files
Description : 
1. Every test dir would be overwritten in this workflow and should be launched a separate action
2. Docker image would be built from ./Dockerfile 
3. Operator would be installed from the present manifest in the dir : config
=> [Test] : e2e Github Action Workflow 

.github/workflows/e2e.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml
related to https://github.com/OT-CONTAINER-KIT/redis-operator/pull/661#issuecomment-1751631068
**Checklist**
=> [Fix] : deploy can not set custom image:tag

tests/e2e/v1beta2/ignore-annots/redis-cluster/00-install.yaml, tests/e2e/v1beta2/ignore-annots/redis-cluster/cluster.yaml, tests/e2e/v1beta2/ignore-annots/redis-cluster/ignore-annots-sts.yaml, tests/e2e/v1beta2/ignore-annots/redis-cluster/ready-sts.yaml, tests/e2e/v1beta2/ignore-annots/redis-standalone/standalone.yaml, tests/e2e/v1beta2/setup/redis-cluster/00-install.yaml, tests/e2e/v1beta2/setup/redis-cluster/cluster.yaml, tests/e2e/v1beta2/setup/redis-cluster/ready-sts.yaml, tests/e2e/v1beta2/setup/redis-standalone/standalone.yaml
1. Update Redis Image to `latest` tag and pull policy set to `always`. 
2. Add Labels to the sts of the redis cluster. 
3. Use the standard way of naming the template. 
Related to : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/656
=> [Test] : e2e Test Update Redis Image to Latest

k8sutils/statefulset.go, k8sutils/statefulset_test.go
=> [Fix] : redis exporter mismatch environment

.github/workflows/operator-ci.yaml, .github/workflows/release-images.yaml, .github/workflows/verify-codegen.yaml, Makefile
verify that the proper code generation is happening or not. 
Fixing the Improper variable name in the workflow.
Now we could use 
`make codegen` - To generate crd + deepcopy 
`make verify-codegen` - To verify if we have any any missing crd ( any other manifests ) or deepcopy
=> feat:  verify codgen in Makefile and Github workflow

k8sutils/cluster-scaling.go, k8sutils/redis-sentinel.go, k8sutils/redis.go, k8sutils/redis_test.go, mocks/utils/utils.go
=> test : Add redis_test.go

.github/workflows/e2e.yaml, controllers/rediscluster_controller.go, k8sutils/cluster-scaling.go, k8sutils/redis.go, tests/_config/kuttl-test.yaml, tests/e2e/v1beta2/scaling/redis-cluster/00-install.yaml, tests/e2e/v1beta2/scaling/redis-cluster/01-scale-up.yaml, tests/e2e/v1beta2/scaling/redis-cluster/02-scale-down.yaml, tests/e2e/v1beta2/scaling/redis-cluster/cluster-scale-up.yaml, tests/e2e/v1beta2/scaling/redis-cluster/cluster.yaml, tests/e2e/v1beta2/scaling/redis-cluster/ready-cluster-scale-up.yaml, tests/e2e/v1beta2/scaling/redis-cluster/ready-cluster.yaml, tests/e2e/v1beta2/scaling/redis-cluster/ready-sts-scale-up.yaml, tests/e2e/v1beta2/scaling/redis-cluster/ready-sts.yaml
1. fix cluster scaling
2. add e2e case
=> [Fix] : cluster scaling 

controllers/rediscluster_controller.go
fix log with following message:
```
{"level":"info","ts":"2023-11-21T21:42:03+08:00","msg":"Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster","RedisCluster":{"name":"redis-cluster-v1beta2","namespace":"kuttl-test-social-bluejay"},"namespace":"kuttl-test-social-bluejay","name":"redis-cluster-v1beta2","reconcileID":"97a22714-ba92-41d6-a76a-0dbb67bf677d"}
```
The result will be ignore when error is non-nil. …
=> [Fix] : returned both a non-zero result and a non-nil error

Makefile
Fix when execute `make test` on darwin arm64:
```
➜  redis-operator-1 git:(master) make test
/Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
/Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
mkdir -p /Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/testbin
test -f /Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/testbin/setup-envtest.sh || curl -sSLo /Users/wuyang/workspace/github.com/drivebyer/redis-operator-1/testbin/setup-envtest.sh …
```
=> fix: specify k8s version which contain darwin arm64

tests/e2e-chainsaw/v1beta2/hostnetwork/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml
=> test: Try Saving Key

tests/e2e-chainsaw/v1beta2/setup/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/replication.yaml
=> test: Add replication to chainsaw setup

tests/e2e-chainsaw/v1beta2/password/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/password/redis-replication/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/password/redis-replication/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/password/redis-replication/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/password/redis-replication/replication.yaml, tests/e2e-chainsaw/v1beta2/password/redis-replication/secret.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/chainsaw-test.yaml
=> test: Try ping and save key on redis replication

k8sutils/statefulset.go, tests/e2e-chainsaw/v1beta2/hostnetwork/redis-cluster/chainsaw-test.yaml
Fixes exporter connect to custom redis port
**Checklist**
=> fix: exporter connect to custom redis port

.github/workflows/e2e-chainsaw.yml, controllers/rediscluster_controller.go, k8sutils/redis-cluster.go, k8sutils/redis-cluster_test.go, k8sutils/services.go, k8sutils/statefulset.go, k8sutils/statefulset_test.go, tests/e2e-chainsaw/v1beta2/hostnetwork/redis-cluster/ready-pod.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/nodeport/redis-cluster/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml, tests/e2e/v1beta2/hostnetwork/redis-cluster/ready-pod.yaml
#183
PS:
> It works only from redis 6 now. When use redis:latest image(7.2.3 for now), the redis-cli --cluster create will hang forever. Maybe there is some break change introduce in redis 7
**Checklist**
=> feat: support create redis cluster by nodeport service

.github/workflows/e2e-chainsaw.yml, k8sutils/const.go, k8sutils/finalizer.go, k8sutils/statefulset.go, tests/_config/chainsaw-configuration.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/pvc-name/redis-cluster/ready-svc.yaml
1. user can customize redis pvc prefix by operator environment
Fixes #438 
**Checklist**
=> feat: add environment to customize data pvc prefix

CONTRIBUTING.md, README.md, docs/content/en/docs/Contribute/_index.md
If we follow the installation guidelines, it failed because the namespace `ot-operators` does not exist. We add a line to create it in the documentation.
**Checklist**
=> docs: add namespace creation

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, k8sutils/poddisruption.go, k8sutils/redis-cluster.go, k8sutils/redis-cluster_test.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-standalone.go, k8sutils/redis.go, k8sutils/services.go, k8sutils/statefulset.go, tests/readme.md
I realised that we create a new k8s client every time we need it. It's quite consuming, we should create it at the start of the controller and use it for his lifetime. We then pass the client down to each functions.
I realised this because we cannot add integration tests with EnvTest if we create a new client every time we need one #748
PS: It looks like the coverage test fail because some code removed was tested so it technically lowers the coverage.
**Checklist**
=> feat: generate k8s client only once

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, main.go
Fix the typo dk8sClinet into dk8sClient.
* Typo fix (non-breaking change which fixes an issue)
**Checklist**
=> chore: fix clinet typo

controllers/rediscluster_controller.go, controllers/redissentinel_controller.go, k8sutils/redis-sentinel.go, k8sutils/redis-sentinel_test.go, k8sutils/status.go
We generated a new dynamic k8s client everytime we needed it. Now we use the one that is generated in main.go only.
**Checklist**
=> Generate dynamic k8s client only once

controllers/rediscluster_controller_test.go, controllers/redisreplication_controller_test.go, controllers/suite_test.go
Add redis replication integration tests. Redis sentinel will be the only one remaining after that.
**Checklist**
=> Add redis replication integration tests

controllers/rediscluster_controller.go
=> chore: enhance log every reconcile redis cluster

controllers/redis_controller_test.go, controllers/rediscluster_controller_test.go, controllers/redisreplication_controller_test.go, controllers/redissentinel_controller_test.go
after remove:
the duration has been reduced from 10 seconds to 6 seconds.
=> test: remove redundant running spec

.github/workflows/e2e-chainsaw.yml, api/common_types.go, config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml, k8sutils/finalizer.go, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/ready-cluster.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-cluster/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-replication/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-replication/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-replication/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-replication/replication.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-standalone/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-standalone/ready-pvc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-standalone/ready-sts.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-standalone/ready-svc.yaml, tests/e2e-chainsaw/v1beta2/keep-pvc/redis-standalone/standalone.yaml
Add field to keep pvc after cr be deleted.
**Checklist**
=> feat: add field to keep pvc after cr be deleted

controllers/redisreplication_controller.go
close https://github.com/OT-CONTAINER-KIT/redis-operator/issues/764
=> chore: enhance log every reconcile redis replication

api/v1beta1/redissentinel_conversion.go
The operator log show:
```
2024/02/19 03:12:45 http: panic serving 10.6.231.10:55106: runtime error: invalid memory address or nil pointer dereference
goroutine 2997 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x194d4a0?, 0x2be6c70?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/OT-CONTAINER-KIT/redis-operator/api/v1beta1.(*RedisSentinel).ConvertFrom(0xc000345a00, {0x1e4f3e8?, 0xc0006f6b40})
/workspace/api/v1beta1/redissentinel_conversion.go:125 +0x4cb
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*webhook).convertObject(0xc00004ef20?, {0x1e48f10, 0xc0006f6b40}, {0x1e49258, 0xc000345a00})
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/webhook/conversion/conversion.go:140 +0x376 …
```
=> fix: nil pointer dereference in conversion webhook

.github/workflows/operator-ci.yaml
Remove the fmt and vet Ci check since they are already covered in the golang CI linters that we are using
=> ci: fmt and vet covered in golang Ci linters by default

.github/workflows/release-images.yaml
Currently the Ci fails constantly due the failing release image.
Release image CI should be halt until fixed.
=> ci: halt failing release

k8sutils/redis-cluster.go, k8sutils/redis-cluster_test.go, k8sutils/services.go, k8sutils/services_test.go
Add test code covering service.go
=> test: service unit Testing

controllers/redissentinel_controller.go, k8sutils/redis-replication.go, tests/e2e-chainsaw/v1beta2/teardown/redis-sentinel/sentinel.yaml
We should wait for the replication cluster to be ready before creating the sentinel cluster.
**Checklist**
=> fix: sentinel waiting for replication pod got ready

k8sutils/cluster-scaling.go, k8sutils/redis.go, k8sutils/redis_test.go
I couldn't get the master-follower replication working in my IPv6 EKS cluster. When the operator tried to set up the replication, the follower logged errors:
```
13 Mar 2024 16:46:20.357 * Connecting to MASTER [2a05:d028:10:482:cae3::3]:6379
13 Mar 2024 16:46:20.360 # Unable to connect to MASTER: Resource temporarily unavailable
```
If I manually ran the `slaveof` command without using brackets, the replication started successfully:
```
13 Mar 2024 16:46:21.250 * Connecting to MASTER 2a05:d028:10:482:cae3::3:6379
13 Mar 2024 16:46:21.250 * MASTER <-> REPLICA sync started
```
This PR modifies the `getRedisServerIP` function to return the plain IPv6 address, as the brackets should only be added when using `<ipv6_addr>:<port>` pairs, as per …
=> fix: m/s replication when using ipv6

.github/workflows/e2e-chainsaw.yml, controllers/redissentinel_controller.go, k8sutils/redis-replication.go, tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/ha-failover/cli-pod.yaml, tests/e2e-chainsaw/v1beta2/ha-failover/replication.yaml, tests/e2e-chainsaw/v1beta2/ha-failover/sentinel.yaml
Fix #802. 
It's acceptable to extend the RequeueAfter period for reconciliation, as the operations performed during this process are limited and primarily involve creating the sentinel StatefulSet and associated services.
**Checklist**
=> fix: ensure sentinel does not observes the failover progress in replication cluster

tests/e2e-chainsaw/v1beta2/acl-user/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/chainsaw-test.yaml
=> test: Show Operator Failed Logs

controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, k8sutils/cluster-scaling.go, k8sutils/cluster-scaling_test.go, k8sutils/redis-cluster.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-standalone.go, k8sutils/redis.go, k8sutils/redis_test.go, k8sutils/statefulset.go, k8sutils/statefulset_test.go, tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
=> test(client): Add Redis Mock Test code

api/v1beta1/redisreplication_types.go, api/v1beta2/redisreplication_types.go, config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, k8sutils/redis.go, tests/e2e-chainsaw/v1beta2/setup/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-replication.yaml
Add redisreplication status masterNode
**Checklist**
=> feat: add redisreplication status masterNode

k8sutils/redis-cluster.go, k8sutils/redis.go, k8sutils/redis_test.go, k8sutils/secrets.go, mocks/utils/utils.go
=> test: Add unit test

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go, k8sutils/finalizer.go, k8sutils/finalizer_test.go
Add common AddFinalizer for all api
**Checklist**
=> refactor: add common AddFinalizer for all api

api/status/redis-cluster_status.go, controllers/rediscluster_controller.go, k8sutils/redis.go, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-cluster.yaml
When we got ready state, the redis cluster should be healthy.
**Checklist**
=> feat: implement redis cluster ready state

.gitignore, k8sutils/statefulset.go, k8sutils/statefulset_test.go
Tests for updatestatefulset functions
=> test: Cover func updatestatefulset 

k8sutils/cluster-scaling.go
`ClusterSlaves` get slave info, we should parse it to get slave node id.
otherwise, the error log:
```
{"level":"error","ts":"2024-04-20T14:50:06+08:00","logger":"controllers.RedisCluster","msg":"Could not execute command","Command":["redis-cli","--cluster","del-node","redis-cluster-v1beta2-leader-0.redis-cluster-v1beta2-leader-headless.default.svc:6379","3acb029fead40752f432c84f9bed2e639119a573 192.168.84.239:6379@16379,redis-cluster-v1beta2-follower-5 slave e3299968586dd457a8dba04fc6c747cecd38510f 0 1713595736542 6 connected"],"Output":">>> Removing node 3acb029fead40752f432c84f9bed2e639119a573 192.168.84.239:6379@16379,redis-cluster-v1beta2-follower-5 slave e3299968586dd457a8dba04fc6c747cecd38510f 0 1713595736542 6 connected from cluster …
```
=> fix: ClusterSlaves result should be cut

controllers/rediscluster_controller.go, tests/_config/chainsaw-configuration.yaml, tests/e2e-chainsaw/v1beta2/scaling/redis-cluster/chainsaw-test.yaml
The operator should rely on the actual status queried from the redis cluster, not just the status it assumes. Otherwise, we might end up with outdated information, leading to downsizing even when the desired leader count is met.
when i scale in cluster from [6 shards](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e-chainsaw/v1beta2/scaling/redis-cluster/cluster-scale-out.yaml) to [3 shards](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e-chainsaw/v1beta2/scaling/redis-cluster/cluster.yaml), the log `Redis cluster is downscaling` show more than 3 times.
see:
```
{"level":"info","ts":"2024-04-21T14:23:18+08:00","logger":"controllers.RedisCluster","msg":"Redis cluster is …
```
=> fix: should get the really leader count when scale in

k8sutils/statefulset.go
=> feat: probe use built-in, discarded healthcheck.sh

k8sutils/redis-cluster.go
> Disclaimer:  new to Go lang. Feel free to author this PR, feedback is welcome.
The `nil` checks in `func generateRedisClusterParams` are ran before `cr.Spec.Storage.$` is referenced, hence causing a runtime panic when the `storage field isn't defined in the manifest.
- Moved `nil` checks on objects before initializing the `statefulSetParameters` struct
- If `cr.Spec.Storage` fails `nil` check,  it initializes it to a new instance of redisv1beta2.Storage{}
⚠️ This might not be the ideal place to perform objects initializations. Please carefully review whether this should exist elsewhere according to your design
* Breaking change / bug fix
**Checklist**
```
{"level":"info","ts":"2024-04-19T17:24:45Z","msg":"Observed a panic in reconciler: runtime …
```
=> fix: runtime panic when `storage` param is empty

docs/content/en/docs/Getting Started/Standalone/_index.md
Update the name and number of pods created by default for redis standalone. When I followed the doc, it worked well but the name of the redis standalone was different.
**Checklist**
=> docs: update standalone pod name

k8sutils/finalizer.go
=> fix: runtime panic when delete rediscluster which disable persistent

controllers/redisreplication_controller.go, k8sutils/const.go, k8sutils/labels.go, k8sutils/pod.go, main.go, tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
=> feat: add redis-role label to redis replication

controllers/redissentinel_controller.go
=> fix: check redis replication after handling finalizer

controllers/redis_controller.go, controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/redissentinel_controller.go
Fixes #801 
After we update the resource, we should return as soon as possible. Otherwise, we will get a conflict error when doing the next update.
**Checklist**
=> fix: return ASAP after handling finalizer

Makefile
Add support for other container engines (podman); still defaults to docker.
**Checklist**
- [NA] Tests have been added/modified and all tests pass.
- [NA] Documentation has been updated or added where necessary.
=> build: add support for other container engines

controllers/redissentinel_controller.go, k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
=> fix: sentinel should not reconcile until replication cluster ready

.github/workflows/publish-image.yaml, controllers/rediscluster_controller.go, controllers/suite_test.go, k8sutils/statefulset.go, main.go, tests/e2e-chainsaw/v1beta2/disable-persistence/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/disable-persistence/redis-cluster/cluster-hscale.yaml, tests/e2e-chainsaw/v1beta2/disable-persistence/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/disable-persistence/redis-cluster/ready-cluster.yaml
=> feat: rolling update sequence from leader to follower

.github/workflows/publish-charts.yaml, charts/redis-operator/Chart.yaml, charts/redis-operator/templates/operator-deployment.yaml, charts/redis-operator/values.yaml, ct.yaml
=> feat: add security context values in operator chart

controllers/rediscluster_controller.go, controllers/redisreplication_controller.go, controllers/suite_test.go, main.go
This change makes the creation process faster, but we will monitor the StatefulSet update. It's okay because it's the best practice for the operator to reconcile.
=> refactor: reconcile on statefulset update

charts/redis-operator/Chart.yaml, charts/redis-operator/templates/operator-deployment.yaml, charts/redis-operator/values.yaml
=> fix: watchNamespace value does not take effect in chart

k8sutils/redis-replication.go, k8sutils/redis-sentinel.go, k8sutils/redis-sentinel_test.go, k8sutils/redis-standalone.go
Fixes #995 
When a user uses an old Redis image that does not have SENTINEL_PORT set as the default environment variable, we must configure SENTINEL_PORT to 26379 in the operator. Otherwise, the Sentinel probe will fail.
**Checklist**
=> fix: add default port to enable `SENTINEL_PORT` environment

config/crd/patches/webhook_in_redis.yaml, config/crd/patches/webhook_in_redisclusters.yaml, config/crd/patches/webhook_in_redisreplications.yaml, config/crd/patches/webhook_in_redissentinels.yaml
The point of the conversion webhook is too update some v1beta1 fields basically and it does nothing for v1beta2. I removed the conversion webhook for v1beta2 version because there is no need to call the conversion for them.
**Checklist**
=> chore: remove latest version for conversion webhook

charts/redis-operator/readme.md, charts/redis-operator/templates/role-binding.yaml, charts/redis-operator/templates/role.yaml, charts/redis-operator/templates/service-account.yaml, charts/redis-operator/values.yaml
In case of a cluster tenant that is not allowed to apply cluster wide resources, the redis operator helm chart cannot be installed as the cluster role and cluster role binding cannot be applied and the chart has no option to disable those resources. Instead, for such scenarios, allow the user to handle rbac provisioning outside of the chart and only link to an externally provisioned service account.
Fixes #1004
**Checklist**
- [ x] Tests have been added/modified and all tests pass.
- [ x] Functionality/bugs have been confirmed to be unchanged or fixed.
- [ x] I have performed a self-review of my own code.
- [ x] Documentation has been updated or added where necessary.
=> feat: allow rbac to pe externally provisioned

charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/templates/redis-sentinel.yaml, charts/redis-sentinel/values.yaml
=> feat: add redisReplicationPassword values to connect secured replication

charts/redis-cluster/templates/redis-cluster.yaml, charts/redis-cluster/values.yaml, charts/redis-replication/Chart.yaml, charts/redis-replication/templates/redis-replication.yaml, charts/redis-replication/values.yaml, charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/templates/redis-sentinel.yaml, charts/redis-sentinel/values.yaml, charts/redis/templates/redis-standalone.yaml, charts/redis/values.yaml
=> fix: unknown field error when upgrade chart

charts/redis/templates/redis-standalone.yaml
The standalone redis template had the incorrect indentation for additionalRedisConfig. As a result any external configs passed through the helm chart were not added to the redis manifest and apply.  A simple indentation fix is all that was needed.
**Checklist**
=> fix: bad indentation on redis standalone additional configs

charts/redis-operator/Chart.yaml, charts/redis-operator/templates/operator-deployment.yaml
A PR to add in tolerations support for the operator deployment.
Fixes #1049
=> feat: add tolerations to operator chart

charts/redis-operator/templates/operator-deployment.yaml, charts/redis-operator/values.yaml
This PR introduces the addition of imagePullSecrets support in the redis-operator Helm chart. This allows users to specify image pull secrets, which is essential for pulling images from private Docker registries.
**Checklist**
=> feat: add image pull secret for redis operator

charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/templates/servicemonitor.yaml
=> feat: add service monitor to redis sentinel chart

charts/redis-operator/Chart.yaml, charts/redis-operator/templates/operator-deployment.yaml
=> feat: add readiness/liveness probe to redis operator chart

charts/redis-operator/Chart.yaml
=> chore: update redis-operator chart version to 0.18.3

Dockerfile, Makefile, api/status/redis-cluster_status.go, go.mod, go.sum, pkg/controllers/rediscluster/rediscluster_controller.go, pkg/k8sutils/redis.go, pkg/k8sutils/redis_test.go, tests/_config/chainsaw-configuration.yaml, tests/e2e-chainsaw/v1beta2/redis-cluster-restart/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/redis-cluster-restart/cluster.yaml, tests/e2e-chainsaw/v1beta2/redis-cluster-restart/failed-cluster.yaml, tests/e2e-chainsaw/v1beta2/redis-cluster-restart/ready-cluster.yaml
ended up closing https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1101 as I was forgetting to sign commits and the git history was getting out of control with having to rebase
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1100
As stated in the above issue, a cluster that has unhealthy leaders as the result of being scaled to zero nodes can be recovered from without having to issue a failover (which leads to data loss).
The failed/disconnected nodes simply need to have their address updated with the IP of the new leader pods.  `CLUSTER MEET` is able to map the address specified to the existing host & port, meaning we don't need to wipe the master & start afresh. If this fails, we fall back to the failover.
* Bug fix (non-breaking …
=> fix: Attempt to repair disconnected/failed master nodes before failing over

charts/redis-sentinel/README.md, charts/redis-sentinel/templates/redis-sentinel.yaml, charts/redis-sentinel/values.yaml
This pull request includes several updates to the Redis Sentinel Helm chart, focusing on the removal of ACL-related configuration and the addition of Pod Disruption Budget (PDB) and probe configurations.
* Removal of ACL Configuration
* Redis Sentinel [does not support](https://github.com/OT-CONTAINER-KIT//redis-operator/blob/909d9e4a7fceee98c6e7e5f43efc95882869cde5/api/v1beta2/redissentinel_types.go#L9-L32) ACL
* Added PDB and probe configuration options (`livenessProbe`, `readinessProbe`) to `charts/redis-sentinel/README.md`.
* Added PDB and probe configuration blocks to `charts/redis-sentinel/templates/redis-sentinel.yaml`.
* Added PDB and probe configuration defaults to `charts/redis-sentinel/values.yaml`.
* Bug fix (non-breaking change which fixes …
=> feat: add PDB and probes, drop unspecified acl in sentinel helm

api/common_types.go, docs/content/en/docs/Configuration/Redis/_index.md, docs/content/en/docs/Configuration/RedisCluster/_index.md, docs/content/en/docs/Configuration/RedisReplication/_index.md, pkg/k8sutils/redis-cluster.go, pkg/k8sutils/redis-replication.go, pkg/k8sutils/redis-sentinel.go, pkg/k8sutils/redis-standalone.go, pkg/util/map.go, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-svc.yaml
#765 
#777 
#785
**Checklist**
=> feat: add master/replica service to redis replication

.github/workflows/ci.yaml, .golangci.yml, Dockerfile, go.mod
=> refactor(deps): bump go from 1.21 to 1.22

charts/redis-sentinel/templates/redis-sentinel.yaml
The pdb values are not applied correctly. This PR is fixing it.
**Checklist**
Previous PR https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1123
=> fix: pdb value mapping in redis-sentinel

charts/redis-cluster/Chart.yaml, charts/redis-cluster/templates/redis-cluster.yaml, charts/redis-replication/Chart.yaml, charts/redis-replication/templates/redis-replication.yaml, charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/templates/redis-sentinel.yaml, charts/redis/Chart.yaml, charts/redis/templates/redis-standalone.yaml
=> fix: chart render error when enable initcontainer

charts/redis-cluster/Chart.yaml, charts/redis-cluster/templates/_helpers.tpl, charts/redis-replication/Chart.yaml, charts/redis-replication/templates/_helpers.tpl, charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/templates/_helpers.tpl, charts/redis/Chart.yaml, charts/redis/templates/_helpers.tpl
- Bumped version and appVersion for redis, redis-cluster, redis-replication, and redis-sentinel charts to 0.16.4, 0.16.4, 0.16.6, and 0.16.8 respectively.
- Enhanced initContainer properties in templates to include the 'enabled' field for better configuration management.
This update ensures consistency across the Redis charts and improves template rendering.
Fixes #1147 
**Checklist**
=> fix: initContainer enabled properties not define in template

api/v1beta2/redisreplication_types.go, api/v1beta2/zz_generated.deepcopy.go, config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml, pkg/controllers/redisreplication/redisreplication_controller.go, pkg/k8sutils/poddisruption.go
Support PDB in redisreplication
**Checklist**
=> feat: support PDB in redisreplication

pkg/controllers/rediscluster/rediscluster_controller.go, pkg/k8sutils/cluster-scaling.go
1. ensure statefulset status is ready before scaling
2. failover command is not effective
3. return directly after failover command
Fixes #1167 
**Checklist**
=> fix: redis-cluster unexpected downscaling (#1167)

.github/workflows/pr-semantics.yaml, pkg/controllers/rediscluster/rediscluster_controller.go, pkg/controllers/redisreplication/redisreplication_controller.go, pkg/controllers/redissentinel/redissentinel_controller.go
- Added new reconciler functions for handling finalizers, annotations, replication, and sentinel management in the RedisSentinel controller.
- Improved error handling and logging for better debugging during reconciliation.
- Updated GitHub Actions workflow to include new job types: standalone, replication, sentinel, and cluster.
This update enhances the functionality and maintainability of the RedisSentinel operator.
Fixes #ISSUE
**Checklist**
=> feat(sentinel): enhance RedisSentinel reconciliation logic and update workflow.

pkg/controllers/rediscluster/rediscluster_controller.go, pkg/k8sutils/cluster-scaling.go, pkg/k8sutils/statefulset.go
ensure that clusterSize and statefulset are consistent
Fixes #ISSUE
* 
**Checklist**
=> fix: reduce the impact of Redis cluster intermediate states

pkg/controllers/redis/redis_controller_test.go, pkg/controllers/redis/testdata/full.yaml, pkg/controllers/rediscluster/rediscluster_controller_test.go, pkg/controllers/rediscluster/testdata/full.yaml, pkg/controllers/redisreplication/redisreplication_controller_test.go, pkg/controllers/redisreplication/testdata/full.yaml, pkg/controllers/redissentinel/redissentinel_controller_test.go, pkg/controllers/redissentinel/testdata/full.yaml
- Updated Redis, RedisCluster, RedisReplication, and RedisSentinel controller tests to utilize YAML testdata files for improved clarity and maintainability.
- Added validation checks for resource creation, owner references, and specifications in the respective test cases.
- Introduced new testdata files for Redis and RedisCluster to streamline test setup and ensure consistent testing across different configurations.
- Enhanced error handling and logging for better debugging during test execution.
This update improves the robustness and reliability of the Redis operator's testing framework.
Fixes #ISSUE
* Breaking change (fix or feature that …
=> test: enhance Redis controllers' test cases with testdata and validation checks

main.go, pkg/controllers/common/events/events.go, pkg/controllers/redis/redis_controller.go, pkg/controllers/redis/redis_controller_suite_test.go, pkg/controllers/rediscluster/rediscluster_controller.go, pkg/controllers/rediscluster/rediscluster_controller_suite_test.go, pkg/controllers/redisreplication/redisreplication_controller.go, pkg/controllers/redisreplication/redisreplication_controller_suite_test.go, pkg/controllers/redissentinel/redissentinel_controller.go, pkg/controllers/redissentinel/redissentinel_controller_suite_test.go
- Introduced a new events package to manage event recording, including a Recorder struct and methods for adding and retrieving events.
- Updated the RedisCluster controller to utilize the event recorder, allowing it to log downscale events.
- Enhanced the main function to initialize the event recorder for the RedisCluster controller.
This update improves observability capabilities for RedisCluster operations.
**Checklist**
=> feat(cluster): add event recording functionality for RedisCluster controller.

pkg/k8sutils/poddisruption.go
Fixes label selector mapping on redisreplication pdb (that previously added in https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1166)
Fixes #ISSUE
**Checklist**
=> fix: label selector mapping on redisreplication pdb

Makefile, api/v1beta2/rediscluster_types.go, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/webhook/manifests.yaml, pkg/controllers/rediscluster/rediscluster_controller_test.go, pkg/controllers/rediscluster/testdata/full.yaml, pkg/k8sutils/redis-cluster.go, pkg/k8sutils/redis-cluster_test.go, pkg/webhook/pod_webhook.go
- Added methods to retrieve resources for Redis leader and follower, allowing for more granular resource management.
- Updated RedisClusterSpec to deprecate the unified resources field in favor of individual configurations for leader and follower.
- Adjusted related tests and YAML configurations to reflect these changes, ensuring consistency and correctness in resource allocation.
This update improves the flexibility and efficiency of resource management in RedisCluster deployments.
PS: this PR is part of https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1188; https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1186
Fixes #ISSUE
**Checklist**
=> feat: enhance RedisCluster resource management by introducing separate resource handling for leader and follower

charts/redis-cluster/Chart.yaml, charts/redis-cluster/README.md, charts/redis-cluster/templates/follower-sm.yaml, charts/redis-cluster/templates/leader-sm.yaml, charts/redis-cluster/values.yaml, charts/redis-replication/Chart.yaml, charts/redis-replication/README.md, charts/redis-replication/templates/servicemonitor.yaml, charts/redis-replication/values.yaml, charts/redis-sentinel/Chart.yaml, charts/redis-sentinel/README.md, charts/redis-sentinel/templates/servicemonitor.yaml, charts/redis-sentinel/values.yaml, charts/redis/Chart.yaml, charts/redis/README.md, charts/redis/templates/servicemonitor.yaml, charts/redis/values.yaml
- Updated version and appVersion for redis, redis-cluster, redis-replication, and redis-sentinel charts to 0.16.5, 0.16.7, and 0.16.9 respectively.
- Introduced `serviceMonitor.extraLabels` in values.yaml and README.md for all Redis charts, allowing users to add custom labels to the ServiceMonitor when enabled.
- Updated templates to utilize the new `extraLabels` configuration for ServiceMonitor.
This change enhances the flexibility of monitoring configurations for Redis deployments.
Fixes #1187
**Checklist**
=> feat: add serviceMonitor.extraLabels support

pkg/controllers/redis/redis_controller.go, pkg/controllers/rediscluster/rediscluster_controller.go, pkg/controllers/redisreplication/redisreplication_controller.go, pkg/controllers/redissentinel/redissentinel_controller.go
skip-reconcile annotation still skipping reconcile even the value is false
Fixes #ISSUE
**Checklist**
=> fix: skip-reconcile annotation still skipping reconcile even the value is false

pkg/k8sutils/secrets.go
=> fix: move secret logging to v1

.github/workflows/publish-charts.yaml
Added actions to publish helm charts to `ghcr.io/ot-container-kit/charts` along side publishing charts to standard helm repo.
**Checklist**
=> feat: added actions to publish charts to github container registry

tests/data-assert/main.go, tests/data-assert/resources.yaml, tests/e2e-chainsaw/v1beta2/setup/ha/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml
- Added new steps in the e2e test for Redis cluster to apply a data assertion tool, `data-assert`, for generating and validating data in the Redis cluster.
- Replaced the previous Redis GET/SET checks with a more comprehensive data generation and validation process using the `data-assert` tool.
- Introduced additional assertions to ensure data consistency after scaling operations.
This update improves the reliability of e2e tests by ensuring data integrity in Redis clusters.
Fixes #ISSUE
**Checklist**
=> test: enhance Redis cluster testing with data assertion scripts

pkg/k8sutils/redis-cluster.go
add missing topologySpreadConstraint on RedisCluster follower
Fixes #ISSUE
**Checklist**
=> fix: add missing topologySpreadConstraint on RedisCluster follower

charts/redis-operator/Chart.lock, charts/redis-operator/Chart.yaml, charts/redis-operator/README.md, charts/redis-operator/README.md.gotmpl, charts/redis-operator/templates/NOTES.txt, charts/redis-operator/templates/_helpers.tpl, charts/redis-operator/values.yaml
- Removed Chart.lock file for cert-manager dependency
- Updated Chart.yaml to remove explicit cert-manager dependency
- Bumped chart version to 0.19.2
- Updated README.md to clarify cert-manager installation instructions
- Modified values.yaml to improve cert-manager and webhook configuration documentation
- Added configuration validation helper in _helpers.tpl
- Introduced NOTES.txt template for helm chart installation guidance
Fixes #1206
**Checklist**
=> feat: update redis-operator cert manager configuration.

pkg/k8sutils/secrets.go
Changed podName to podName.namespace in the tls.config in secrets.go so that is it possible to issue *.namespace wildcard TLS certificate with cert-manager.
Fixes #763 
**Checklist**
- [*] Functionality/bugs have been confirmed to be unchanged or fixed.
- [*] I have performed a self-review of my own code.
- [*] Documentation has been updated or added where necessary.
=> Changed certificate serverName to pod+namespace

pkg/k8sutils/pod.go, pkg/util/strings.go
- Added JSON pointer escaping for label keys
- Implemented retry mechanism for label patching
- Enhanced error handling and logging
- Added validation for empty labels
- Created utility function for JSON pointer escaping in util package
#1217
**Checklist**
=> fix: improve pod label patching with error handling and retry mechanism

charts/redis-cluster/README.md, charts/redis-cluster/templates/redis-cluster.yaml, charts/redis-cluster/values.yaml, charts/redis-replication/README.md, charts/redis-replication/templates/redis-replication.yaml, charts/redis-replication/values.yaml, charts/redis-sentinel/README.md, charts/redis-sentinel/templates/redis-sentinel.yaml, charts/redis-sentinel/values.yaml, charts/redis/README.md, charts/redis/templates/redis-standalone.yaml, charts/redis/values.yaml
Add ability to configure securityContext for redis-exporter in redis helm charts:
- redis
- redis-cluster
- redis-replication
- redis-sentinel
Supported in:
- v1beta1 & v1beta2: Redis, RedisCluster, RedisReplication Operator CRDs
- v1beta2 only: RedisSentinel Operator CRD
This aligns with existing redis operator CRD functionality.
**Checklist**
This change is required to support restricted pod security admission standards for the redis-exporter containers.
=> feat: add securityContext config in chart for redis-exporter

pkg/k8sutils/redis-cluster.go, pkg/k8sutils/redis-replication.go, pkg/k8sutils/redis-sentinel.go, pkg/k8sutils/redis-standalone.go
Make recreate statefulset only trigger when value true
Fixes #ISSUE
**Checklist**
=> fix: make recreate statefulset only trigger when value true

main.go, pkg/controllers/redis/redis_controller.go, pkg/controllers/redis/redis_controller_suite_test.go, pkg/controllers/rediscluster/rediscluster_controller.go, pkg/controllers/rediscluster/rediscluster_controller_suite_test.go, pkg/controllers/redisreplication/redisreplication_controller.go, pkg/controllers/redisreplication/redisreplication_controller_suite_test.go, pkg/controllers/redissentinel/redissentinel_controller.go, pkg/controllers/redissentinel/redissentinel_controller_suite_test.go
configurable operator maxConcurrentReconciles: running multiple instances of (Replication, Sentinel, Cluster) will make the reconcile faster without the need to wait one by one processing.
Fixes #ISSUE
**Checklist**
=> feat: configurable operator maxConcurrentReconciles

.github/workflows/auto-rebase.yaml
Add a GitHub Actions workflow to enable automatic rebasing of pull requests via comment commands `/rebase` and `/autosquash`
The workflow allows repository collaborators to trigger a rebase of a pull request by commenting `/rebase` or perform an autosquash rebase with `/autosquash`.
Fixes #ISSUE
**Checklist**
=> ci: add GitHub workflow for automatic PR rebase

pkg/k8sutils/redis.go
- Updated `RedisClusterStatusHealth` function to use `cr.Spec.Port` instead of hardcoded 6379 port.
- Ensured the command uses the specified port from the RedisCluster spec.
- Added handling for existing password secret and TLS arguments.
This change allows the Redis port to be configurable through the `cr.Spec.Port` field, improving flexibility and configurability of the Redis cluster setup.
- Verified that the Redis cluster health check uses the specified port from the RedisCluster spec.
- Ensured that the command execution works correctly with the provided port, password, and TLS arguments.
=> fix: replace hardcoded Redis port 6379 with configurable port from cr.Spec.Port

docs/content/en/docs/Advance Configuration/Upgrading/_index.md, docs/content/en/docs/CRD Reference/Redis API/_index.md, pkg/k8sutils/const.go, pkg/k8sutils/redis-cluster.go, pkg/k8sutils/redis-replication.go, pkg/k8sutils/redis-sentinel.go, pkg/k8sutils/redis-standalone.go, pkg/k8sutils/statefulset.go, pkg/k8sutils/statefulset_test.go
This PR will expand the capability of current `"redis.opstreelabs.in/recreate-statefulset"`, to make the users have more control to deal with recreating process of the StatefulSet,
For example: Recreating the Statefulset (with foreground delete) on, will make the Pod of Sentinel entirely terminated, 
with the setting of [orphan](https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/#deleting-a-statefulset) --> `"redis.opstreelabs.in/recreate-statefulset-strategy: orphan"` will keep the Pod up and running and will make the administrator have more control on it (for example: to avoid downtime).
Fixes #ISSUE
* Breaking change (fix …
=> feat: add recreate-stateful-strategy, orphan, background, foreground(default)

charts/redis-cluster/README.md, charts/redis-cluster/templates/redis-cluster.yaml, charts/redis-cluster/values.yaml, charts/redis-operator/README.md, charts/redis-operator/README.md.gotmpl, charts/redis-operator/templates/cert-manager.yaml, charts/redis-operator/values.yaml
Following what was done in [pull/1180](https://github.com/OT-CONTAINER-KIT/redis-operator/pull/1180), there is an annotation that can be used to enforce leader-follower anti affinity using a mutating webhook. But it's not possible to use it from the provided Helm Charts.
I added the following:
- Possibility to add the annotation on the `RedisCluster` resource by using `redisCluster.enableMasterSlaveAntiAffinity`
- Possibility to disable the creation of cert-manager `Issuer` (which might be not required) in case someone wants to use an existing one for the `Certificate`
- Possibility to create it as a `ClusterIssuer`, if desired. And also to use this kind of issuer in the certificate. …
=> feat: Add support for anti affinity configuration in helm charts

pkg/k8sutils/services.go, pkg/util/map.go
This PR addresses two issues:
1. **Fix Svc Finalizer Issue:**  
The service (svc) finalizer was mistakenly being removed. This PR includes changes that ensure the finalizer is preserved during updates, preventing unintended deletions.
2. **Introduce Utility Functions:**  
Two new generic utility functions have been added:
- **MergePreservingExistingKeys:** Merges key-value pairs from a source map into a destination map, preserving existing keys in the destination.
- **CopyMap:** Creates a shallow copy of a given map by leveraging the `MergeMap` function.
=> fix: svc finalizer removed.

go.mod, go.sum, pkg/k8sutils/redis-sentinel.go, pkg/k8sutils/redis-sentinel_test.go
Guarantee to avoid bad master ip on Sentinel, in edge/worse cases, usually we are facing replication instance pointing to `master 0.0.0.0`
Fixes #ISSUE
**Checklist**
=> feat: guarantee to avoid bad master ip on Sentinel

pkg/k8sutils/redis.go
The operator contains a race condition that results in a broken cluster where all `redis` instances (including the previous master) are set to be replicas with an empty master IP. It doesn't seem to ever recover from that state, and requires a manual intervention to bring the cluster back to life.
This is because [`CreateMasterSlaveReplication`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/main/pkg/k8sutils/redis.go#L649) doesn't check whether the IP of the master node is empty, and happily iterates through all instances and sets them to replicas. It attempts to exclude the master by comparing the IPs, that can be empty:
```go
realMasterPodIP := getRedisServerIP(ctx, client, realMasterInfo)
for i := 0; i < len(masterPods); i++ {
if masterPods[i] != realMasterPod …
```
=> fix: race condition resulting in permanently broken Redis cluster

.gitignore, cmd/manager/main.go, go.mod, go.sum, pkg/agent/bootstrap/generate_config.go, pkg/features/features.go, pkg/k8sutils/const.go, pkg/k8sutils/statefulset.go, pkg/k8sutils/statefulset_test.go
- Introduced a new feature gate to enable generating Redis configuration using an init container.
- Updated the main.go to parse feature gates from command-line flags.
- Enhanced statefulset definition to conditionally include init containers based on feature gate status.
- Added necessary volume and volume mount definitions for configuration management.
This change improves flexibility in Redis operator deployment configurations.
https://github.com/OT-CONTAINER-KIT/redis-operator/issues/766
**Checklist**
=> feat: add feature gates for sentinel configuration generation in init container

Dockerfile, Makefile, internal/image/operator_image.go, pkg/agent/bootstrap/generate_redis_config.go, pkg/k8sutils/const.go, pkg/k8sutils/statefulset.go
- Added IMG argument to Dockerfile for dynamic image handling.
- Updated LDFLAGS in Dockerfile to set operator image during build.
- Modified Makefile to pass IMG as a build argument in Docker commands.
- Introduced internal package for operator image retrieval.
- Removed hardcoded operator image reference from const.go.
These changes improve the flexibility and maintainability of the operator image configuration.
#766 
**Checklist**
=> feat: support redis configuration generation in init container

.github/workflows/publish-image.yaml, Makefile, charts/redis-operator/Chart.yaml, charts/redis-operator/crds/redis.redis.opstreelabs.in_redis.yaml, charts/redis-operator/crds/redis.redis.opstreelabs.in_redisclusters.yaml, charts/redis-operator/crds/redis.redis.opstreelabs.in_redisreplications.yaml, charts/redis-operator/crds/redis.redis.opstreelabs.in_redissentinels.yaml, pkg/agent/sidecar.go
- Bumped operator version to 0.20.0 in Makefile and Chart.yaml.
- Simplified GitHub Actions workflow by renaming jobs and removing unnecessary comments.
- Added hostPort field to CRDs for Redis resources to support additional configuration.
- Deleted unused sidecar.go file to clean up the codebase.
These changes improve versioning clarity and streamline the CI/CD process.
Fixes #ISSUE
**Checklist**
=> chore: update version to 0.20.0 and enhance CI workflow

Makefile, pkg/k8sutils/redis.go
Test were panic due to continuation on the error.
We need to return if we have found the error
```
Will run 1 of 1 specs
•panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x188ba15]
goroutine 251 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1da
```
**Checklist**
Tried Running Test More that 1 one …
=> fix: handle panic when retrieving StatefulSet in GetRedisNodesByRole

docs/content/en/docs/Getting Started/Sentinel/_index.md
`fsGroup` is only available under `PodSecurityContext` in the CRD unless I'm not seeing it right.
* Documentation
**Checklist**
=> docs: fix redis sentinel example

.github/workflows/ci.yaml, internal/k8sutils/pvc.go, internal/k8sutils/statefulset.go, internal/k8sutils/statefulset_test.go, tests/e2e-chainsaw/v1beta2/setup/redis-replication/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-replication/ready-pvc-resized.yaml
Resizing STS VolumeClaimTemplates is currently broken because the change does not get detected and acted on. This is an unintended side effect of #1322 where the `newStateful` has its VCT changes reset and then a patch is calculated. If you've only changed the VCT, then because of the reset no changes are detected and the function returns early, leading to not resizing the PVCs, not replacing the StatefulSet (if recreation is enabled), and not setting the storageCapacity annotation. 
The change now takes into account whether STS recreation is enabled or not. If it is, it makes sense to not reset the VCT and recreate the STS. This then solves the TODO of handling the case when the STS is scaled out -- the new PVCs will have the intended new size.
The change is slightly …
=> fix: VCT resize detection logic; add support for scaling out with new VCT size

internal/controller/rediscluster/rediscluster_controller.go
fix: Service updated before Statefulset during Reconcilation(#1347)
Fixes #1347
**Checklist**
I have only fixed the cluster creation and label updates with this pull request. Any other test cases needs to be tested.
=> fix: Service updated before Statefulset during Reconcilation #1347

docs/content/en/docs/Getting Started/Cluster/_index.md
This pull request corrects an error in the YAML installation example for Redis Cluster found in the documentation under `Installation > Getting Started > Cluster`.
The sample manifest incorrectly used `spec.securityContext` for the `RedisCluster` Custom Resource (apiVersion `redis.redis.opstreelabs.in/v1beta2`). This has been updated to the correct field `spec.podSecurityContext`.
This change ensures that users following the YAML installation guide can successfully deploy a Redis cluster without encountering a `BadRequest` error due to an unknown field.
Fixes : https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1345
**Checklist**
The error message encountered when applying …
=> docs: fix Redis Cluster YAML Manifest Example (#1345)

.github/workflows/auto-release.yaml
…tag push
- Introduced a new workflow that triggers on tag pushes matching 'v*'.
- Configured steps to check for existing releases, generate release notes, and create a new GitHub release if none exists.
- This automation streamlines the release process for the Redis operator.
Fixes #ISSUE
**Checklist**
=> chore: add GitHub Actions workflow for automatic release creation on tag push

docs/content/en/docs/Getting Started/Sentinel/_index.md
- Added a note emphasizing that the `redisReplicationName` parameter must reference an existing RedisReplication resource.
- Included a reminder to deploy a RedisReplication resource before installing Sentinel to ensure proper functionality.
This update clarifies the prerequisites for using Redis Sentinel effectively.
Fixes #1290
**Checklist**
=> docs: add important notes on redisReplicationName parameter in Sentinel documentation

charts/redis-cluster/Chart.yaml, charts/redis-cluster/README.md, charts/redis-cluster/templates/_helpers.tpl, charts/redis-cluster/values.yaml
- Updated Chart.yaml to version 0.17.0.
- Added livenessProbe and readinessProbe configurations to values.yaml for both leader and follower.
- Updated _helpers.tpl to include livenessProbe and readinessProbe in the rendered templates.
This update enhances the Redis cluster's health monitoring capabilities.
Fixes #1328
**Checklist**
=> feat: add liveness/readiness probes to values.yaml and templates

api/redisreplication/v1beta2/redisreplication_types.go, api/redissentinel/v1beta2/redissentinel_types.go, internal/cmd/manager/manager.go, internal/controller/common/redis/check.go, internal/controller/common/redis/heal.go, internal/controller/redis/redis_controller.go, internal/controller/rediscluster/rediscluster_controller.go, internal/controller/redisreplication/redisreplication_controller.go, internal/controller/redissentinel/redissentinel_controller.go, internal/controller/redissentinel/redissentinel_controller_suite_test.go, internal/controllerutil/controller_common.go, internal/k8sutils/redis-sentinel.go, internal/k8sutils/redis-sentinel_test.go, internal/service/redis/client.go
- Added Checker and Healer interfaces to manage Redis replication and sentinel health.
- Introduced methods for checking master status and resetting sentinels.
- Updated RedisSentinelReconciler to utilize the new health check and healing functionalities.
This enhancement improves the reliability and self-healing capabilities of the Redis operator.
Fixes #436 
**Checklist**
=> feat: avoid sentinel restart after replication failover

internal/k8sutils/labels.go, internal/k8sutils/labels_test.go, internal/k8sutils/statefulset.go, internal/k8sutils/statefulset_test.go, tests/e2e-chainsaw/v1beta2/setup/redis-ha/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-ha/ha.yaml
- Add extractStatefulSetSelectorLabels() to filter stable labels for StatefulSet selectors
- Modify generateStatefulSetsDef() to use filtered selector labels while preserving all labels in metadata/templates
- Revert Service selector changes as Service selectors are mutable and don't require filtering
- Add comprehensive tests for StatefulSet selector label filtering
This PR addresses a critical issue where StatefulSet updates fail with "forbidden" errors when using Helm charts to deploy Redis instances. The problem occurs because:
Helm automatically adds mutable labels like helm.sh/chart: redis-replication-4.5.6 and app.kubernetes.io/version: v7.0.12 to all resources
redis-operator used all metadata labels for StatefulSet selectors, including these mutable Helm labels
StatefulSet …
=> fix: resolve StatefulSet selector immutability issues

api/common/v1beta2/common_types.go, api/common/v1beta2/zz_generated.deepcopy.go, config/crd/bases/redis.redis.opstreelabs.in_redis.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml, config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml, config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml, internal/k8sutils/redis-cluster.go, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/ready-svc.yaml
- Introduced new methods in KubernetesConfig to determine if the bus port should be included for headless and additional services.
- Updated ServiceConfig and Service structs to include an optional IncludeBusPort field.
- Enhanced service creation logic to conditionally add the bus port based on the new configuration.
- Updated CRD definitions to reflect the new IncludeBusPort field and its description.
- Modified e2e tests to validate the inclusion of the bus port in service configurations.
This enhancement allows for better customization of Redis service configurations, particularly for Redis cluster mode.
Fixes #1039
Add includeBusPort Configuration for Redis Cluster Services
This PR adds a new includeBusPort field to control Redis bus port (16379) inclusion in cluster …
=> feat: add bus port configuration for Redis cluster services

internal/controller/rediscluster/rediscluster_controller.go, internal/k8sutils/cluster-scaling.go
Rather than always picking the first leader node, round robin among the remaining leaders during a scale in event. This should help distribute the load on the remaining nodes during transfer, reduce the chance for OOMKills, and make the subsequent rebalance command more efficient as there will be fewer slots to move. 
Fixes [#1334](https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1334)
**Checklist**
```
...
{"level":"info","ts":"2025-06-18T12:45:16Z","msg":"Transferring 1638 slots from shard 9 to shard 1","controller":"rediscluster","controllerGroup":"[redis.redis.opstreelabs.in](http://redis.redis.opstreelabs.in/)","controllerKind":"RedisCluster","RedisCluster":{ …
```
=> feat: Round robin where to transfer cluster shards when scaling in a Redis Cluster

charts/redis-operator/Chart.yaml, charts/redis-operator/templates/service.yaml
- Updated the redis-operator version in Chart.yaml to 0.21.1.
- Added a conditional statement in service.yaml to include webhook configuration based on user-defined values.
fix #1400 
Fixes #ISSUE
**Checklist**
=> fix: add webhook condition to service template

docs/layouts/partials/page-meta-links.html
This PR corrects the "Edit this page" link in the documentation, ensuring it points to the accurate file path within the repository for direct editing.
=> docs: Update edit URL path

internal/controller/redissentinel/redissentinel_controller.go, tests/e2e-chainsaw/v1beta2/setup/redis-sentinel/sentinel.yaml
Add watch resource of Redis Sentinel, so a sentinel is reconciled, even after restarting due to deletion or failure.
Fixes #1429.
=> fix: sentinel controller should reconcile on statefulset updated

README.md, docs/content/en/docs/Redis Overview/_index.md
This pull request addresses two main documentation updates:
1.  **Slack Channel Link Update:** The `README.md` file's Slack channel invitation link was outdated. This PR updates it to the correct and active invitation link, ensuring users can easily join our community Slack channel.
2.  **Sharding Section Organization:** In `docs/content/en/docs/Redis Overview/_index.md`, the "Sharding" explanation was slightly redundant and could be clearer. This change refines the text to provide a more concise and accurate description of sharding, removing duplicate or confusing sentences. It also ensures the accompanying image correctly illustrates the concept.
* Documentation update
**Checklist**
=> docs: Update slack channel link and improve sharding section clarity

.github/workflows/ci.yaml, .yamllint.yml, internal/agent/bootstrap/sentinel/config.go, internal/controller/common/redis/check.go, internal/controller/common/redis/heal.go, internal/controller/common/service.go, internal/controller/rediscluster/rediscluster_controller.go, internal/controller/redisreplication/redisreplication_controller.go, internal/controller/redissentinel/redissentinel_controller.go, internal/k8sutils/redis-sentinel.go, internal/k8sutils/redis.go, internal/k8sutils/redis_test.go, internal/k8sutils/secrets.go, internal/service/redis/client.go, internal/util/cryptutil/tls_verify.go, tests/data-assert/main.go, tests/data-assert/resources.yaml, tests/data-assert/resources.yaml.tmpl, tests/e2e-chainsaw/v1beta2/setup/redis-ha/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-ha/ha.yaml
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1462 https://github.com/OT-CONTAINER-KIT/redis/issues/91
When creating Redis with Sentinel, the Sentinel could not connect to Redis because it did not have TLS enabled. In this PR, we set tls-replication to yes for Sentinel, which instructs Sentinel to use a TLS connection for replication. This requires enabling the agent init container by setting `--set featureGates.GenerateConfigInInitContainer=true`.
When updating the redis-role label of the pod, the operator needs to connect to Redis to check its role. This PR adds TLS support when performing this role check.
**Checklist**
=> fix: tls connection broken in replication with sentinel

README.md, internal/k8sutils/redis-cluster_test.go, internal/k8sutils/redis-sentinel_test.go, internal/k8sutils/redis-standalone_test.go, internal/k8sutils/statefulset.go, internal/k8sutils/statefulset_test.go, tests/testdata/redis-cluster.yaml, tests/testdata/redis-sentinel.yaml, tests/testdata/redis-standalone.yaml
This PR fixes an issue where the `initContainer.securityContext` configuration was not being applied to the operator-generated `init-config` container when the `GenerateConfigInInitContainer` feature flag is enabled.
When the `GenerateConfigInInitContainer` feature flag is enabled, the operator creates two init containers:
1. `init-config`: Operator-generated container for Redis configuration generation
2. `init{name}`: User-defined init container
The issue was that the `init-config` container was created without applying the `securityContext` from the user's `initContainer` configuration, while the user-defined init container correctly received the security context.
Modified the `generateInitContainerDef` function in `internal/k8sutils/statefulset.go` to apply the `SecurityContext` from …
=> Fix initContainer.securityContext not being applied to operator-generated init containers

internal/controller/common/redis/check.go, internal/k8sutils/redis-sentinel.go
I noticed that you previously fixed the bug where starting Sentinel in a single-node setup didn't work: https://github.com/OT-CONTAINER-KIT/redis-operator/pull/523. However, in order to address another bug — where the cluster would mistakenly enter the single-node processing logic after restarting all pods (related link: https://github.com/OT-CONTAINER-KIT/redis-operator/pull/964) — this piece of logic was removed. To solve this problem, I've made some optimizations to distinguish between single-node mode and cluster mode using the clusterSize in CR's spec.
Fixes #521 
**Checklist**
=> fix: Fix the issue where Sentinel fails to work when starting 1 Master Replication

internal/k8sutils/statefulset.go, internal/k8sutils/statefulset_test.go
closes #1479
Adds the extra volume in `additionalRedisConfig` to the volumes, instead of replacing the existing "config" volume.
Fixes #1479
**Checklist**
- [-] Documentation has been updated or added where necessary.
- This MR does not address `spec.redisConfig.additionalRedisConfig` on redisclusters being ignored. There's a semantic issue of how this should behave
- LMK if docs should be updated
=> fix: do not remove default config volume when providing additional config

go.mod, go.sum, internal/agent/bootstrap/redis/config.go, internal/agent/bootstrap/redis/config_test.go, internal/k8sutils/redis.go, internal/util/net.go, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/chainsaw-test.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/cluster.yaml, tests/e2e-chainsaw/v1beta2/setup/redis-cluster/secret.yaml
- **Set FQDN for `cluster-announce-hostname`**
- Refactored Redis cluster configuration generation to improve IP handling and code structure
- Replace exec commands with Go-native implementations using fqdn.FqdnHostname() for hostname resolution
- Add proper IP address handling in nodes.conf file updates using regex patterns
This change is only applicable when the GenerateConfigInInitContainer feature gate is enabled.
Fixes #1441
**Checklist**
=> fix: cluster TLS configuration for init-config container

charts/redis-replication/templates/replication-service.yaml, charts/redis-replication/values.yaml, charts/redis-sentinel/templates/service.yaml, charts/redis-sentinel/values.yaml, charts/redis/templates/service.yaml, charts/redis/values.yaml
This pull request adds the ability to specify custom nodePort numbers when exposing Redis services through NodePort type. Users can now define a specific port number in the Redis CR configuration, providing better control over external service access.
The implementation includes:
- Added `nodePort` field to the service configuration in the Redis CRD
- Updated service creation logic to use the specified nodePort when provided
- Added validation to ensure nodePort is within the valid Kubernetes range (30000-32767)
- Backward compatibility maintained - when nodePort is not specified, Kubernetes continues to auto-assign ports
Fixes #1487 
**Checklist**
This feature is …
=> feat: Helm chart: NodePort specification #1487

internal/cmd/manager/cmd.go, internal/controller/common/redis/check.go, internal/controller/rediscluster/rediscluster_controller.go, internal/k8sutils/redis.go, internal/service/redis/client.go
**Problem**
The Operator has a logic issue in managing clusters: in a single-node deployment, the cluster initialization process is skipped. This results in unassigned slots within the cluster and an abnormal cluster status.
The current logic uses the CLUSTER NODES command to check the number of cluster nodes. If the node count does not match the value defined in the Custom Resource (CR), it considers the cluster is uninitialized and triggers slot assignment via initialization logic.
However, in a single-node scenario, the node count remains 1 regardless of whether the cluster is actually initialized. This causes the initialization logic to be incorrectly skipped, leading to empty slots and abnormal cluster status.
**Solution**
To resolve this, we’ve modified the logic as …
=> fix: Unassigned slots and abnormal status in single-node cluster due to skipped initialization

README.md
- fix wrong helm chart installation commands in readme
- add information about serviceMonitor
I'm not sure why you still set the old prometheus annotation labels: 
```yaml
annotations:
redis.opstreelabs.in: "true"
prometheus.io/scrape: "true"
prometheus.io/port: "9121"
```
They are not used anymore nowadays and since you have the serviceMonitor anways ... but ok, leaving this at it is ;) 
Regards,
Kilian
=> docs: Improve Readme

internal/k8sutils/redis.go, internal/k8sutils/redis_test.go
closes #1517 
The command passed to Redis must come after the flags. This struct allows for flags to be set after the command for redis is defined.
Fixes #1517 
**Checklist**
- In theory this struct could be used everywhere, but this is the only place that passes a command that is interpreted by _redis's interpreter_ rather than a cli command of redis-cli.
- I inlined the BaseCommand. Seemed much simpler than writing an algorithmic way to determine this
- It can't be used just for `CreateSingleLeaderRedisCommand` since the TLS flags are added later
- This solution removes the temporal coupling that would be introduced by just reordering the statements that add flags
=> fix: proper order for flags to redis-cli command

internal/k8sutils/statefulset.go
Ensure the init-config container has the same resource as the main redis cluster to help scheduling on correct nodes etc
Fixes #1502 
**Checklist**
=> fix: Fixes init-config container resources to match main container.

.github/workflows/publish-image.yaml, charts/redis-operator/Chart.yaml, charts/redis-operator/templates/operator-deployment.yaml
- Add missing IMG build-arg to Docker builds in publish workflow
- Add OPERATOR_IMAGE env var to Helm deployment template
- Fix GHCR build to use correct registry URL instead of Quay.io
- Ensures init-config containers use proper versioned images instead of :latest
Resolves issue where init-config containers defaulted to :latest tag
when GenerateConfigInInitContainer feature gate was enabled.
Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/1512
**Checklist**
=> fix: Set correct operator image in init containers
